package com.xinyi.dao;

import com.xinyi.bean.XinyiImport;
import com.xinyi.bean.XinyiSupplierInfo;
import com.xinyi.bean.XinyiSupplierInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface XinyiSupplierInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinyi_supplier_info
     *
     * @mbg.generated Tue Jul 30 12:31:49 CST 2019
     */
    long countByExample(XinyiSupplierInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinyi_supplier_info
     *
     * @mbg.generated Tue Jul 30 12:31:49 CST 2019
     */
    int deleteByExample(XinyiSupplierInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinyi_supplier_info
     *
     * @mbg.generated Tue Jul 30 12:31:49 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinyi_supplier_info
     *
     * @mbg.generated Tue Jul 30 12:31:49 CST 2019
     */
    int insert(XinyiSupplierInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinyi_supplier_info
     *
     * @mbg.generated Tue Jul 30 12:31:49 CST 2019
     */
    int insertSelective(XinyiSupplierInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinyi_supplier_info
     *
     * @mbg.generated Tue Jul 30 12:31:49 CST 2019
     */
    List<XinyiSupplierInfo> selectByExample(XinyiSupplierInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinyi_supplier_info
     *
     * @mbg.generated Tue Jul 30 12:31:49 CST 2019
     */
    XinyiSupplierInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinyi_supplier_info
     *
     * @mbg.generated Tue Jul 30 12:31:49 CST 2019
     */
    int updateByExampleSelective(@Param("record") XinyiSupplierInfo record, @Param("example") XinyiSupplierInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinyi_supplier_info
     *
     * @mbg.generated Tue Jul 30 12:31:49 CST 2019
     */
    int updateByExample(@Param("record") XinyiSupplierInfo record, @Param("example") XinyiSupplierInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinyi_supplier_info
     *
     * @mbg.generated Tue Jul 30 12:31:49 CST 2019
     */
    int updateByPrimaryKeySelective(XinyiSupplierInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinyi_supplier_info
     *
     * @mbg.generated Tue Jul 30 12:31:49 CST 2019
     */
    int updateByPrimaryKey(XinyiSupplierInfo record);

	public List<XinyiSupplierInfo> selectAll();
}