package com.xinyi.dao;

import com.xinyi.bean.XinyiAction;
import com.xinyi.bean.XinyiActionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;


public interface XinyiActionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinyi_action
     *
     * @mbg.generated Fri May 24 23:04:22 CST 2019
     */
    long countByExample(XinyiActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinyi_action
     *
     * @mbg.generated Fri May 24 23:04:22 CST 2019
     */
    int deleteByExample(XinyiActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinyi_action
     *
     * @mbg.generated Fri May 24 23:04:22 CST 2019
     */
    int deleteByPrimaryKey(Integer actionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinyi_action
     *
     * @mbg.generated Fri May 24 23:04:22 CST 2019
     */
    int insert(XinyiAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinyi_action
     *
     * @mbg.generated Fri May 24 23:04:22 CST 2019
     */
    int insertSelective(XinyiAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinyi_action
     *
     * @mbg.generated Fri May 24 23:04:22 CST 2019
     */
    List<XinyiAction> selectByExample(XinyiActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinyi_action
     *
     * @mbg.generated Fri May 24 23:04:22 CST 2019
     */
    XinyiAction selectByPrimaryKey(Integer actionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinyi_action
     *
     * @mbg.generated Fri May 24 23:04:22 CST 2019
     */
    int updateByExampleSelective(@Param("record") XinyiAction record, @Param("example") XinyiActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinyi_action
     *
     * @mbg.generated Fri May 24 23:04:22 CST 2019
     */
    int updateByExample(@Param("record") XinyiAction record, @Param("example") XinyiActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinyi_action
     *
     * @mbg.generated Fri May 24 23:04:22 CST 2019
     */
    int updateByPrimaryKeySelective(XinyiAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinyi_action
     *
     * @mbg.generated Fri May 24 23:04:22 CST 2019
     */
    int updateByPrimaryKey(XinyiAction record);
}