package com.xinyi.dao;

import com.xinyi.bean.XinyiRoles;
import com.xinyi.bean.XinyiRolesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface XinyiRolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinyi_roles
     *
     * @mbg.generated Fri May 24 23:04:22 CST 2019
     */
    long countByExample(XinyiRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinyi_roles
     *
     * @mbg.generated Fri May 24 23:04:22 CST 2019
     */
    int deleteByExample(XinyiRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinyi_roles
     *
     * @mbg.generated Fri May 24 23:04:22 CST 2019
     */
    int deleteByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinyi_roles
     *
     * @mbg.generated Fri May 24 23:04:22 CST 2019
     */
    int insert(XinyiRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinyi_roles
     *
     * @mbg.generated Fri May 24 23:04:22 CST 2019
     */
    int insertSelective(XinyiRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinyi_roles
     *
     * @mbg.generated Fri May 24 23:04:22 CST 2019
     */
    List<XinyiRoles> selectByExample(XinyiRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinyi_roles
     *
     * @mbg.generated Fri May 24 23:04:22 CST 2019
     */
    XinyiRoles selectByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinyi_roles
     *
     * @mbg.generated Fri May 24 23:04:22 CST 2019
     */
    int updateByExampleSelective(@Param("record") XinyiRoles record, @Param("example") XinyiRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinyi_roles
     *
     * @mbg.generated Fri May 24 23:04:22 CST 2019
     */
    int updateByExample(@Param("record") XinyiRoles record, @Param("example") XinyiRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinyi_roles
     *
     * @mbg.generated Fri May 24 23:04:22 CST 2019
     */
    int updateByPrimaryKeySelective(XinyiRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinyi_roles
     *
     * @mbg.generated Fri May 24 23:04:22 CST 2019
     */
    int updateByPrimaryKey(XinyiRoles record);
}