package com.xinyi.dao;

import com.xinyi.bean.XinyiMaterial;
import com.xinyi.bean.XinyiMaterialExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface XinyiMaterialMapper {
	
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_material
	 * @mbg.generated  Mon Feb 24 23:04:51 CST 2020
	 */
	long countByExample(XinyiMaterialExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_material
	 * @mbg.generated  Mon Feb 24 23:04:51 CST 2020
	 */
	int deleteByExample(XinyiMaterialExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_material
	 * @mbg.generated  Mon Feb 24 23:04:51 CST 2020
	 */
	int deleteByPrimaryKey(String materialId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_material
	 * @mbg.generated  Mon Feb 24 23:04:51 CST 2020
	 */
	int insert(XinyiMaterial record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_material
	 * @mbg.generated  Mon Feb 24 23:04:51 CST 2020
	 */
	int insertSelective(XinyiMaterial record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_material
	 * @mbg.generated  Mon Feb 24 23:04:51 CST 2020
	 */
	List<XinyiMaterial> selectByExample(XinyiMaterialExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_material
	 * @mbg.generated  Mon Feb 24 23:04:51 CST 2020
	 */
	XinyiMaterial selectByPrimaryKey(String materialId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_material
	 * @mbg.generated  Mon Feb 24 23:04:51 CST 2020
	 */
	int updateByExampleSelective(@Param("record") XinyiMaterial record, @Param("example") XinyiMaterialExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_material
	 * @mbg.generated  Mon Feb 24 23:04:51 CST 2020
	 */
	int updateByExample(@Param("record") XinyiMaterial record, @Param("example") XinyiMaterialExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_material
	 * @mbg.generated  Mon Feb 24 23:04:51 CST 2020
	 */
	int updateByPrimaryKeySelective(XinyiMaterial record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_material
	 * @mbg.generated  Mon Feb 24 23:04:51 CST 2020
	 */
	int updateByPrimaryKey(XinyiMaterial record);

	List<XinyiMaterial> selectAll();
}