package com.xinyi.dao;

import com.xinyi.bean.XinyiImage;
import com.xinyi.bean.XinyiImageExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface XinyiImageMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_image
	 * @mbg.generated  Tue Sep 10 19:58:49 CST 2019
	 */
	long countByExample(XinyiImageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_image
	 * @mbg.generated  Tue Sep 10 19:58:49 CST 2019
	 */
	int deleteByExample(XinyiImageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_image
	 * @mbg.generated  Tue Sep 10 19:58:49 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_image
	 * @mbg.generated  Tue Sep 10 19:58:49 CST 2019
	 */
	int insert(XinyiImage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_image
	 * @mbg.generated  Tue Sep 10 19:58:49 CST 2019
	 */
	int insertSelective(XinyiImage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_image
	 * @mbg.generated  Tue Sep 10 19:58:49 CST 2019
	 */
	List<XinyiImage> selectByExample(XinyiImageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_image
	 * @mbg.generated  Tue Sep 10 19:58:49 CST 2019
	 */
	XinyiImage selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_image
	 * @mbg.generated  Tue Sep 10 19:58:49 CST 2019
	 */
	int updateByExampleSelective(@Param("record") XinyiImage record, @Param("example") XinyiImageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_image
	 * @mbg.generated  Tue Sep 10 19:58:49 CST 2019
	 */
	int updateByExample(@Param("record") XinyiImage record, @Param("example") XinyiImageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_image
	 * @mbg.generated  Tue Sep 10 19:58:49 CST 2019
	 */
	int updateByPrimaryKeySelective(XinyiImage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_image
	 * @mbg.generated  Tue Sep 10 19:58:49 CST 2019
	 */
	int updateByPrimaryKey(XinyiImage record);

	List<XinyiImage> selectAll();
}