package com.xinyi.dao;

import com.xinyi.bean.XinyiBatchStock;
import com.xinyi.bean.XinyiBatchStockExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface XinyiBatchStockMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_batch_stock
	 * @mbg.generated  Tue Feb 25 14:45:58 CST 2020
	 */
	long countByExample(XinyiBatchStockExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_batch_stock
	 * @mbg.generated  Tue Feb 25 14:45:58 CST 2020
	 */
	int deleteByExample(XinyiBatchStockExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_batch_stock
	 * @mbg.generated  Tue Feb 25 14:45:58 CST 2020
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_batch_stock
	 * @mbg.generated  Tue Feb 25 14:45:58 CST 2020
	 */
	int insert(XinyiBatchStock record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_batch_stock
	 * @mbg.generated  Tue Feb 25 14:45:58 CST 2020
	 */
	int insertSelective(XinyiBatchStock record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_batch_stock
	 * @mbg.generated  Tue Feb 25 14:45:58 CST 2020
	 */
	List<XinyiBatchStock> selectByExample(XinyiBatchStockExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_batch_stock
	 * @mbg.generated  Tue Feb 25 14:45:58 CST 2020
	 */
	XinyiBatchStock selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_batch_stock
	 * @mbg.generated  Tue Feb 25 14:45:58 CST 2020
	 */
	int updateByExampleSelective(@Param("record") XinyiBatchStock record,
			@Param("example") XinyiBatchStockExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_batch_stock
	 * @mbg.generated  Tue Feb 25 14:45:58 CST 2020
	 */
	int updateByExample(@Param("record") XinyiBatchStock record, @Param("example") XinyiBatchStockExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_batch_stock
	 * @mbg.generated  Tue Feb 25 14:45:58 CST 2020
	 */
	int updateByPrimaryKeySelective(XinyiBatchStock record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_batch_stock
	 * @mbg.generated  Tue Feb 25 14:45:58 CST 2020
	 */
	int updateByPrimaryKey(XinyiBatchStock record);
}