package com.xinyi.dao;

import com.xinyi.bean.XinyiPicking;
import com.xinyi.bean.XinyiPickingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface XinyiPickingMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_picking
	 * @mbg.generated  Thu Aug 01 11:47:35 CST 2019
	 */
	long countByExample(XinyiPickingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_picking
	 * @mbg.generated  Thu Aug 01 11:47:35 CST 2019
	 */
	int deleteByExample(XinyiPickingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_picking
	 * @mbg.generated  Thu Aug 01 11:47:35 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_picking
	 * @mbg.generated  Thu Aug 01 11:47:35 CST 2019
	 */
	int insert(XinyiPicking record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_picking
	 * @mbg.generated  Thu Aug 01 11:47:35 CST 2019
	 */
	int insertSelective(XinyiPicking record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_picking
	 * @mbg.generated  Thu Aug 01 11:47:35 CST 2019
	 */
	List<XinyiPicking> selectByExample(XinyiPickingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_picking
	 * @mbg.generated  Thu Aug 01 11:47:35 CST 2019
	 */
	XinyiPicking selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_picking
	 * @mbg.generated  Thu Aug 01 11:47:35 CST 2019
	 */
	int updateByExampleSelective(@Param("record") XinyiPicking record, @Param("example") XinyiPickingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_picking
	 * @mbg.generated  Thu Aug 01 11:47:35 CST 2019
	 */
	int updateByExample(@Param("record") XinyiPicking record, @Param("example") XinyiPickingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_picking
	 * @mbg.generated  Thu Aug 01 11:47:35 CST 2019
	 */
	int updateByPrimaryKeySelective(XinyiPicking record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_picking
	 * @mbg.generated  Thu Aug 01 11:47:35 CST 2019
	 */
	int updateByPrimaryKey(XinyiPicking record);


    List<XinyiPicking> selectAll();
}