package com.xinyi.dao;

import com.xinyi.bean.XinyiManufactures;
import com.xinyi.bean.XinyiManufacturesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface XinyiManufacturesMapper {
	//这个表放厂家
	//自己写的
	@Select("select * from xinyi_manufactures")
	public List<XinyiManufactures> selectAll();
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinyi_manufactures
     *
     * @mbg.generated Sun Jul 14 18:25:40 CST 2019
     */
    long countByExample(XinyiManufacturesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinyi_manufactures
     *
     * @mbg.generated Sun Jul 14 18:25:40 CST 2019
     */
    int deleteByExample(XinyiManufacturesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinyi_manufactures
     *
     * @mbg.generated Sun Jul 14 18:25:40 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinyi_manufactures
     *
     * @mbg.generated Sun Jul 14 18:25:40 CST 2019
     */
    int insert(XinyiManufactures record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinyi_manufactures
     *
     * @mbg.generated Sun Jul 14 18:25:40 CST 2019
     */
    int insertSelective(XinyiManufactures record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinyi_manufactures
     *
     * @mbg.generated Sun Jul 14 18:25:40 CST 2019
     */
    List<XinyiManufactures> selectByExample(XinyiManufacturesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinyi_manufactures
     *
     * @mbg.generated Sun Jul 14 18:25:40 CST 2019
     */
    XinyiManufactures selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinyi_manufactures
     *
     * @mbg.generated Sun Jul 14 18:25:40 CST 2019
     */
    int updateByExampleSelective(@Param("record") XinyiManufactures record, @Param("example") XinyiManufacturesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinyi_manufactures
     *
     * @mbg.generated Sun Jul 14 18:25:40 CST 2019
     */
    int updateByExample(@Param("record") XinyiManufactures record, @Param("example") XinyiManufacturesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinyi_manufactures
     *
     * @mbg.generated Sun Jul 14 18:25:40 CST 2019
     */
    int updateByPrimaryKeySelective(XinyiManufactures record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinyi_manufactures
     *
     * @mbg.generated Sun Jul 14 18:25:40 CST 2019
     */
    int updateByPrimaryKey(XinyiManufactures record);
}