package com.xinyi.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.xinyi.bean.XinyiImport;
import com.xinyi.bean.XinyiImportExample;


@Mapper
public interface XinyiImportMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_import
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	long countByExample(XinyiImportExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_import
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	int deleteByExample(XinyiImportExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_import
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_import
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	int insert(XinyiImport record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_import
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	int insertSelective(XinyiImport record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_import
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	List<XinyiImport> selectByExample(XinyiImportExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_import
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	XinyiImport selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_import
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	int updateByExampleSelective(@Param("record") XinyiImport record, @Param("example") XinyiImportExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_import
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	int updateByExample(@Param("record") XinyiImport record, @Param("example") XinyiImportExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_import
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	int updateByPrimaryKeySelective(XinyiImport record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_import
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	int updateByPrimaryKey(XinyiImport record);

	public List<XinyiImport> selectAll();
	
	XinyiImport selectLastOne();
}