package com.xinyi.dao;

import com.xinyi.bean.XinyiUserRoleExample;
import com.xinyi.bean.XinyiUserRoleKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface XinyiUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinyi_user_role
     *
     * @mbg.generated Sat May 25 19:44:58 CST 2019
     */
    long countByExample(XinyiUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinyi_user_role
     *
     * @mbg.generated Sat May 25 19:44:58 CST 2019
     */
    int deleteByExample(XinyiUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinyi_user_role
     *
     * @mbg.generated Sat May 25 19:44:58 CST 2019
     */
    int deleteByPrimaryKey(XinyiUserRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinyi_user_role
     *
     * @mbg.generated Sat May 25 19:44:58 CST 2019
     */
    int insert(XinyiUserRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinyi_user_role
     *
     * @mbg.generated Sat May 25 19:44:58 CST 2019
     */
    int insertSelective(XinyiUserRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinyi_user_role
     *
     * @mbg.generated Sat May 25 19:44:58 CST 2019
     */
    List<XinyiUserRoleKey> selectByExample(XinyiUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinyi_user_role
     *
     * @mbg.generated Sat May 25 19:44:58 CST 2019
     */
    int updateByExampleSelective(@Param("record") XinyiUserRoleKey record, @Param("example") XinyiUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xinyi_user_role
     *
     * @mbg.generated Sat May 25 19:44:58 CST 2019
     */
    int updateByExample(@Param("record") XinyiUserRoleKey record, @Param("example") XinyiUserRoleExample example);
}