package com.xinyi.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class XinyiModifyhistoryExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table xinyi_modifyhistory
	 * @mbg.generated  Sun Jul 14 18:16:22 CST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table xinyi_modifyhistory
	 * @mbg.generated  Sun Jul 14 18:16:22 CST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table xinyi_modifyhistory
	 * @mbg.generated  Sun Jul 14 18:16:22 CST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_modifyhistory
	 * @mbg.generated  Sun Jul 14 18:16:22 CST 2019
	 */
	public XinyiModifyhistoryExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_modifyhistory
	 * @mbg.generated  Sun Jul 14 18:16:22 CST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_modifyhistory
	 * @mbg.generated  Sun Jul 14 18:16:22 CST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_modifyhistory
	 * @mbg.generated  Sun Jul 14 18:16:22 CST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_modifyhistory
	 * @mbg.generated  Sun Jul 14 18:16:22 CST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_modifyhistory
	 * @mbg.generated  Sun Jul 14 18:16:22 CST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_modifyhistory
	 * @mbg.generated  Sun Jul 14 18:16:22 CST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_modifyhistory
	 * @mbg.generated  Sun Jul 14 18:16:22 CST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_modifyhistory
	 * @mbg.generated  Sun Jul 14 18:16:22 CST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_modifyhistory
	 * @mbg.generated  Sun Jul 14 18:16:22 CST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_modifyhistory
	 * @mbg.generated  Sun Jul 14 18:16:22 CST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table xinyi_modifyhistory
	 * @mbg.generated  Sun Jul 14 18:16:22 CST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andModifyidIsNull() {
			addCriterion("modifyId is null");
			return (Criteria) this;
		}

		public Criteria andModifyidIsNotNull() {
			addCriterion("modifyId is not null");
			return (Criteria) this;
		}

		public Criteria andModifyidEqualTo(Integer value) {
			addCriterion("modifyId =", value, "modifyid");
			return (Criteria) this;
		}

		public Criteria andModifyidNotEqualTo(Integer value) {
			addCriterion("modifyId <>", value, "modifyid");
			return (Criteria) this;
		}

		public Criteria andModifyidGreaterThan(Integer value) {
			addCriterion("modifyId >", value, "modifyid");
			return (Criteria) this;
		}

		public Criteria andModifyidGreaterThanOrEqualTo(Integer value) {
			addCriterion("modifyId >=", value, "modifyid");
			return (Criteria) this;
		}

		public Criteria andModifyidLessThan(Integer value) {
			addCriterion("modifyId <", value, "modifyid");
			return (Criteria) this;
		}

		public Criteria andModifyidLessThanOrEqualTo(Integer value) {
			addCriterion("modifyId <=", value, "modifyid");
			return (Criteria) this;
		}

		public Criteria andModifyidIn(List<Integer> values) {
			addCriterion("modifyId in", values, "modifyid");
			return (Criteria) this;
		}

		public Criteria andModifyidNotIn(List<Integer> values) {
			addCriterion("modifyId not in", values, "modifyid");
			return (Criteria) this;
		}

		public Criteria andModifyidBetween(Integer value1, Integer value2) {
			addCriterion("modifyId between", value1, value2, "modifyid");
			return (Criteria) this;
		}

		public Criteria andModifyidNotBetween(Integer value1, Integer value2) {
			addCriterion("modifyId not between", value1, value2, "modifyid");
			return (Criteria) this;
		}

		public Criteria andModifynameIsNull() {
			addCriterion("modifyname is null");
			return (Criteria) this;
		}

		public Criteria andModifynameIsNotNull() {
			addCriterion("modifyname is not null");
			return (Criteria) this;
		}

		public Criteria andModifynameEqualTo(String value) {
			addCriterion("modifyname =", value, "modifyname");
			return (Criteria) this;
		}

		public Criteria andModifynameNotEqualTo(String value) {
			addCriterion("modifyname <>", value, "modifyname");
			return (Criteria) this;
		}

		public Criteria andModifynameGreaterThan(String value) {
			addCriterion("modifyname >", value, "modifyname");
			return (Criteria) this;
		}

		public Criteria andModifynameGreaterThanOrEqualTo(String value) {
			addCriterion("modifyname >=", value, "modifyname");
			return (Criteria) this;
		}

		public Criteria andModifynameLessThan(String value) {
			addCriterion("modifyname <", value, "modifyname");
			return (Criteria) this;
		}

		public Criteria andModifynameLessThanOrEqualTo(String value) {
			addCriterion("modifyname <=", value, "modifyname");
			return (Criteria) this;
		}

		public Criteria andModifynameLike(String value) {
			addCriterion("modifyname like", value, "modifyname");
			return (Criteria) this;
		}

		public Criteria andModifynameNotLike(String value) {
			addCriterion("modifyname not like", value, "modifyname");
			return (Criteria) this;
		}

		public Criteria andModifynameIn(List<String> values) {
			addCriterion("modifyname in", values, "modifyname");
			return (Criteria) this;
		}

		public Criteria andModifynameNotIn(List<String> values) {
			addCriterion("modifyname not in", values, "modifyname");
			return (Criteria) this;
		}

		public Criteria andModifynameBetween(String value1, String value2) {
			addCriterion("modifyname between", value1, value2, "modifyname");
			return (Criteria) this;
		}

		public Criteria andModifynameNotBetween(String value1, String value2) {
			addCriterion("modifyname not between", value1, value2, "modifyname");
			return (Criteria) this;
		}

		public Criteria andModifytimeIsNull() {
			addCriterion("modifytime is null");
			return (Criteria) this;
		}

		public Criteria andModifytimeIsNotNull() {
			addCriterion("modifytime is not null");
			return (Criteria) this;
		}

		public Criteria andModifytimeEqualTo(Date value) {
			addCriterionForJDBCDate("modifytime =", value, "modifytime");
			return (Criteria) this;
		}

		public Criteria andModifytimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("modifytime <>", value, "modifytime");
			return (Criteria) this;
		}

		public Criteria andModifytimeGreaterThan(Date value) {
			addCriterionForJDBCDate("modifytime >", value, "modifytime");
			return (Criteria) this;
		}

		public Criteria andModifytimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("modifytime >=", value, "modifytime");
			return (Criteria) this;
		}

		public Criteria andModifytimeLessThan(Date value) {
			addCriterionForJDBCDate("modifytime <", value, "modifytime");
			return (Criteria) this;
		}

		public Criteria andModifytimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("modifytime <=", value, "modifytime");
			return (Criteria) this;
		}

		public Criteria andModifytimeIn(List<Date> values) {
			addCriterionForJDBCDate("modifytime in", values, "modifytime");
			return (Criteria) this;
		}

		public Criteria andModifytimeNotIn(List<Date> values) {
			addCriterionForJDBCDate("modifytime not in", values, "modifytime");
			return (Criteria) this;
		}

		public Criteria andModifytimeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("modifytime between", value1, value2, "modifytime");
			return (Criteria) this;
		}

		public Criteria andModifytimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("modifytime not between", value1, value2, "modifytime");
			return (Criteria) this;
		}

		public Criteria andModifymanagerIsNull() {
			addCriterion("modifymanager is null");
			return (Criteria) this;
		}

		public Criteria andModifymanagerIsNotNull() {
			addCriterion("modifymanager is not null");
			return (Criteria) this;
		}

		public Criteria andModifymanagerEqualTo(String value) {
			addCriterion("modifymanager =", value, "modifymanager");
			return (Criteria) this;
		}

		public Criteria andModifymanagerNotEqualTo(String value) {
			addCriterion("modifymanager <>", value, "modifymanager");
			return (Criteria) this;
		}

		public Criteria andModifymanagerGreaterThan(String value) {
			addCriterion("modifymanager >", value, "modifymanager");
			return (Criteria) this;
		}

		public Criteria andModifymanagerGreaterThanOrEqualTo(String value) {
			addCriterion("modifymanager >=", value, "modifymanager");
			return (Criteria) this;
		}

		public Criteria andModifymanagerLessThan(String value) {
			addCriterion("modifymanager <", value, "modifymanager");
			return (Criteria) this;
		}

		public Criteria andModifymanagerLessThanOrEqualTo(String value) {
			addCriterion("modifymanager <=", value, "modifymanager");
			return (Criteria) this;
		}

		public Criteria andModifymanagerLike(String value) {
			addCriterion("modifymanager like", value, "modifymanager");
			return (Criteria) this;
		}

		public Criteria andModifymanagerNotLike(String value) {
			addCriterion("modifymanager not like", value, "modifymanager");
			return (Criteria) this;
		}

		public Criteria andModifymanagerIn(List<String> values) {
			addCriterion("modifymanager in", values, "modifymanager");
			return (Criteria) this;
		}

		public Criteria andModifymanagerNotIn(List<String> values) {
			addCriterion("modifymanager not in", values, "modifymanager");
			return (Criteria) this;
		}

		public Criteria andModifymanagerBetween(String value1, String value2) {
			addCriterion("modifymanager between", value1, value2, "modifymanager");
			return (Criteria) this;
		}

		public Criteria andModifymanagerNotBetween(String value1, String value2) {
			addCriterion("modifymanager not between", value1, value2, "modifymanager");
			return (Criteria) this;
		}

		public Criteria andMaterialnameIsNull() {
			addCriterion("materialname is null");
			return (Criteria) this;
		}

		public Criteria andMaterialnameIsNotNull() {
			addCriterion("materialname is not null");
			return (Criteria) this;
		}

		public Criteria andMaterialnameEqualTo(String value) {
			addCriterion("materialname =", value, "materialname");
			return (Criteria) this;
		}

		public Criteria andMaterialnameNotEqualTo(String value) {
			addCriterion("materialname <>", value, "materialname");
			return (Criteria) this;
		}

		public Criteria andMaterialnameGreaterThan(String value) {
			addCriterion("materialname >", value, "materialname");
			return (Criteria) this;
		}

		public Criteria andMaterialnameGreaterThanOrEqualTo(String value) {
			addCriterion("materialname >=", value, "materialname");
			return (Criteria) this;
		}

		public Criteria andMaterialnameLessThan(String value) {
			addCriterion("materialname <", value, "materialname");
			return (Criteria) this;
		}

		public Criteria andMaterialnameLessThanOrEqualTo(String value) {
			addCriterion("materialname <=", value, "materialname");
			return (Criteria) this;
		}

		public Criteria andMaterialnameLike(String value) {
			addCriterion("materialname like", value, "materialname");
			return (Criteria) this;
		}

		public Criteria andMaterialnameNotLike(String value) {
			addCriterion("materialname not like", value, "materialname");
			return (Criteria) this;
		}

		public Criteria andMaterialnameIn(List<String> values) {
			addCriterion("materialname in", values, "materialname");
			return (Criteria) this;
		}

		public Criteria andMaterialnameNotIn(List<String> values) {
			addCriterion("materialname not in", values, "materialname");
			return (Criteria) this;
		}

		public Criteria andMaterialnameBetween(String value1, String value2) {
			addCriterion("materialname between", value1, value2, "materialname");
			return (Criteria) this;
		}

		public Criteria andMaterialnameNotBetween(String value1, String value2) {
			addCriterion("materialname not between", value1, value2, "materialname");
			return (Criteria) this;
		}

		public Criteria andMaterialidIsNull() {
			addCriterion("materialId is null");
			return (Criteria) this;
		}

		public Criteria andMaterialidIsNotNull() {
			addCriterion("materialId is not null");
			return (Criteria) this;
		}

		public Criteria andMaterialidEqualTo(String value) {
			addCriterion("materialId =", value, "materialid");
			return (Criteria) this;
		}

		public Criteria andMaterialidNotEqualTo(String value) {
			addCriterion("materialId <>", value, "materialid");
			return (Criteria) this;
		}

		public Criteria andMaterialidGreaterThan(String value) {
			addCriterion("materialId >", value, "materialid");
			return (Criteria) this;
		}

		public Criteria andMaterialidGreaterThanOrEqualTo(String value) {
			addCriterion("materialId >=", value, "materialid");
			return (Criteria) this;
		}

		public Criteria andMaterialidLessThan(String value) {
			addCriterion("materialId <", value, "materialid");
			return (Criteria) this;
		}

		public Criteria andMaterialidLessThanOrEqualTo(String value) {
			addCriterion("materialId <=", value, "materialid");
			return (Criteria) this;
		}

		public Criteria andMaterialidLike(String value) {
			addCriterion("materialId like", value, "materialid");
			return (Criteria) this;
		}

		public Criteria andMaterialidNotLike(String value) {
			addCriterion("materialId not like", value, "materialid");
			return (Criteria) this;
		}

		public Criteria andMaterialidIn(List<String> values) {
			addCriterion("materialId in", values, "materialid");
			return (Criteria) this;
		}

		public Criteria andMaterialidNotIn(List<String> values) {
			addCriterion("materialId not in", values, "materialid");
			return (Criteria) this;
		}

		public Criteria andMaterialidBetween(String value1, String value2) {
			addCriterion("materialId between", value1, value2, "materialid");
			return (Criteria) this;
		}

		public Criteria andMaterialidNotBetween(String value1, String value2) {
			addCriterion("materialId not between", value1, value2, "materialid");
			return (Criteria) this;
		}

		public Criteria andMaterialunitIsNull() {
			addCriterion("materialunit is null");
			return (Criteria) this;
		}

		public Criteria andMaterialunitIsNotNull() {
			addCriterion("materialunit is not null");
			return (Criteria) this;
		}

		public Criteria andMaterialunitEqualTo(String value) {
			addCriterion("materialunit =", value, "materialunit");
			return (Criteria) this;
		}

		public Criteria andMaterialunitNotEqualTo(String value) {
			addCriterion("materialunit <>", value, "materialunit");
			return (Criteria) this;
		}

		public Criteria andMaterialunitGreaterThan(String value) {
			addCriterion("materialunit >", value, "materialunit");
			return (Criteria) this;
		}

		public Criteria andMaterialunitGreaterThanOrEqualTo(String value) {
			addCriterion("materialunit >=", value, "materialunit");
			return (Criteria) this;
		}

		public Criteria andMaterialunitLessThan(String value) {
			addCriterion("materialunit <", value, "materialunit");
			return (Criteria) this;
		}

		public Criteria andMaterialunitLessThanOrEqualTo(String value) {
			addCriterion("materialunit <=", value, "materialunit");
			return (Criteria) this;
		}

		public Criteria andMaterialunitLike(String value) {
			addCriterion("materialunit like", value, "materialunit");
			return (Criteria) this;
		}

		public Criteria andMaterialunitNotLike(String value) {
			addCriterion("materialunit not like", value, "materialunit");
			return (Criteria) this;
		}

		public Criteria andMaterialunitIn(List<String> values) {
			addCriterion("materialunit in", values, "materialunit");
			return (Criteria) this;
		}

		public Criteria andMaterialunitNotIn(List<String> values) {
			addCriterion("materialunit not in", values, "materialunit");
			return (Criteria) this;
		}

		public Criteria andMaterialunitBetween(String value1, String value2) {
			addCriterion("materialunit between", value1, value2, "materialunit");
			return (Criteria) this;
		}

		public Criteria andMaterialunitNotBetween(String value1, String value2) {
			addCriterion("materialunit not between", value1, value2, "materialunit");
			return (Criteria) this;
		}

		public Criteria andMaterialnumberIsNull() {
			addCriterion("materialnumber is null");
			return (Criteria) this;
		}

		public Criteria andMaterialnumberIsNotNull() {
			addCriterion("materialnumber is not null");
			return (Criteria) this;
		}

		public Criteria andMaterialnumberEqualTo(Integer value) {
			addCriterion("materialnumber =", value, "materialnumber");
			return (Criteria) this;
		}

		public Criteria andMaterialnumberNotEqualTo(Integer value) {
			addCriterion("materialnumber <>", value, "materialnumber");
			return (Criteria) this;
		}

		public Criteria andMaterialnumberGreaterThan(Integer value) {
			addCriterion("materialnumber >", value, "materialnumber");
			return (Criteria) this;
		}

		public Criteria andMaterialnumberGreaterThanOrEqualTo(Integer value) {
			addCriterion("materialnumber >=", value, "materialnumber");
			return (Criteria) this;
		}

		public Criteria andMaterialnumberLessThan(Integer value) {
			addCriterion("materialnumber <", value, "materialnumber");
			return (Criteria) this;
		}

		public Criteria andMaterialnumberLessThanOrEqualTo(Integer value) {
			addCriterion("materialnumber <=", value, "materialnumber");
			return (Criteria) this;
		}

		public Criteria andMaterialnumberIn(List<Integer> values) {
			addCriterion("materialnumber in", values, "materialnumber");
			return (Criteria) this;
		}

		public Criteria andMaterialnumberNotIn(List<Integer> values) {
			addCriterion("materialnumber not in", values, "materialnumber");
			return (Criteria) this;
		}

		public Criteria andMaterialnumberBetween(Integer value1, Integer value2) {
			addCriterion("materialnumber between", value1, value2, "materialnumber");
			return (Criteria) this;
		}

		public Criteria andMaterialnumberNotBetween(Integer value1, Integer value2) {
			addCriterion("materialnumber not between", value1, value2, "materialnumber");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table xinyi_modifyhistory
	 * @mbg.generated  Sun Jul 14 18:16:22 CST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table xinyi_modifyhistory
     *
     * @mbg.generated do_not_delete_during_merge Sat Jul 06 15:36:26 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}