package com.xinyi.bean;

public class XinyiBatchStock {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_batch_stock.id
	 * @mbg.generated  Tue Aug 06 10:30:46 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_batch_stock.batch
	 * @mbg.generated  Tue Aug 06 10:30:46 CST 2019
	 */
	private String batch;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_batch_stock.number
	 * @mbg.generated  Tue Aug 06 10:30:46 CST 2019
	 */
	private Integer number;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_batch_stock.name
	 * @mbg.generated  Tue Aug 06 10:30:46 CST 2019
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_batch_stock.price
	 * @mbg.generated  Tue Aug 06 10:30:46 CST 2019
	 */
	private Double price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_batch_stock.plus
	 * @mbg.generated  Tue Aug 06 10:30:46 CST 2019
	 */
	private String plus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_batch_stock.materialId
	 * @mbg.generated  Tue Aug 06 10:30:46 CST 2019
	 */
	private String materialid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_batch_stock.manufacturer
	 * @mbg.generated  Tue Aug 06 10:30:46 CST 2019
	 */
	private String manufacturer;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_batch_stock.supplier
	 * @mbg.generated  Tue Aug 06 10:30:46 CST 2019
	 */
	private String supplier;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_batch_stock.id
	 * @return  the value of xinyi_batch_stock.id
	 * @mbg.generated  Tue Aug 06 10:30:46 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_batch_stock.id
	 * @param id  the value for xinyi_batch_stock.id
	 * @mbg.generated  Tue Aug 06 10:30:46 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_batch_stock.batch
	 * @return  the value of xinyi_batch_stock.batch
	 * @mbg.generated  Tue Aug 06 10:30:46 CST 2019
	 */
	public String getBatch() {
		return batch;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_batch_stock.batch
	 * @param batch  the value for xinyi_batch_stock.batch
	 * @mbg.generated  Tue Aug 06 10:30:46 CST 2019
	 */
	public void setBatch(String batch) {
		this.batch = batch;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_batch_stock.number
	 * @return  the value of xinyi_batch_stock.number
	 * @mbg.generated  Tue Aug 06 10:30:46 CST 2019
	 */
	public Integer getNumber() {
		return number;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_batch_stock.number
	 * @param number  the value for xinyi_batch_stock.number
	 * @mbg.generated  Tue Aug 06 10:30:46 CST 2019
	 */
	public void setNumber(Integer number) {
		this.number = number;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_batch_stock.name
	 * @return  the value of xinyi_batch_stock.name
	 * @mbg.generated  Tue Aug 06 10:30:46 CST 2019
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_batch_stock.name
	 * @param name  the value for xinyi_batch_stock.name
	 * @mbg.generated  Tue Aug 06 10:30:46 CST 2019
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_batch_stock.price
	 * @return  the value of xinyi_batch_stock.price
	 * @mbg.generated  Tue Aug 06 10:30:46 CST 2019
	 */
	public Double getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_batch_stock.price
	 * @param price  the value for xinyi_batch_stock.price
	 * @mbg.generated  Tue Aug 06 10:30:46 CST 2019
	 */
	public void setPrice(Double price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_batch_stock.plus
	 * @return  the value of xinyi_batch_stock.plus
	 * @mbg.generated  Tue Aug 06 10:30:46 CST 2019
	 */
	public String getPlus() {
		return plus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_batch_stock.plus
	 * @param plus  the value for xinyi_batch_stock.plus
	 * @mbg.generated  Tue Aug 06 10:30:46 CST 2019
	 */
	public void setPlus(String plus) {
		this.plus = plus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_batch_stock.materialId
	 * @return  the value of xinyi_batch_stock.materialId
	 * @mbg.generated  Tue Aug 06 10:30:46 CST 2019
	 */
	public String getMaterialid() {
		return materialid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_batch_stock.materialId
	 * @param materialid  the value for xinyi_batch_stock.materialId
	 * @mbg.generated  Tue Aug 06 10:30:46 CST 2019
	 */
	public void setMaterialid(String materialid) {
		this.materialid = materialid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_batch_stock.manufacturer
	 * @return  the value of xinyi_batch_stock.manufacturer
	 * @mbg.generated  Tue Aug 06 10:30:46 CST 2019
	 */
	public String getManufacturer() {
		return manufacturer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_batch_stock.manufacturer
	 * @param manufacturer  the value for xinyi_batch_stock.manufacturer
	 * @mbg.generated  Tue Aug 06 10:30:46 CST 2019
	 */
	public void setManufacturer(String manufacturer) {
		this.manufacturer = manufacturer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_batch_stock.supplier
	 * @return  the value of xinyi_batch_stock.supplier
	 * @mbg.generated  Tue Aug 06 10:30:46 CST 2019
	 */
	public String getSupplier() {
		return supplier;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_batch_stock.supplier
	 * @param supplier  the value for xinyi_batch_stock.supplier
	 * @mbg.generated  Tue Aug 06 10:30:46 CST 2019
	 */
	public void setSupplier(String supplier) {
		this.supplier = supplier;
	}
}