package com.xinyi.bean;

import java.util.ArrayList;
import java.util.List;

public class XinyiImportExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table xinyi_import
	 * @mbg.generated  Sat Jul 27 13:57:14 CST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table xinyi_import
	 * @mbg.generated  Sat Jul 27 13:57:14 CST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table xinyi_import
	 * @mbg.generated  Sat Jul 27 13:57:14 CST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_import
	 * @mbg.generated  Sat Jul 27 13:57:14 CST 2019
	 */
	public XinyiImportExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_import
	 * @mbg.generated  Sat Jul 27 13:57:14 CST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_import
	 * @mbg.generated  Sat Jul 27 13:57:14 CST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_import
	 * @mbg.generated  Sat Jul 27 13:57:14 CST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_import
	 * @mbg.generated  Sat Jul 27 13:57:14 CST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_import
	 * @mbg.generated  Sat Jul 27 13:57:14 CST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_import
	 * @mbg.generated  Sat Jul 27 13:57:14 CST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_import
	 * @mbg.generated  Sat Jul 27 13:57:14 CST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_import
	 * @mbg.generated  Sat Jul 27 13:57:14 CST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_import
	 * @mbg.generated  Sat Jul 27 13:57:14 CST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_import
	 * @mbg.generated  Sat Jul 27 13:57:14 CST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table xinyi_import
	 * @mbg.generated  Sat Jul 27 13:57:14 CST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andMaterialIdIsNull() {
			addCriterion("material_id is null");
			return (Criteria) this;
		}

		public Criteria andMaterialIdIsNotNull() {
			addCriterion("material_id is not null");
			return (Criteria) this;
		}

		public Criteria andMaterialIdEqualTo(String value) {
			addCriterion("material_id =", value, "materialId");
			return (Criteria) this;
		}

		public Criteria andMaterialIdNotEqualTo(String value) {
			addCriterion("material_id <>", value, "materialId");
			return (Criteria) this;
		}

		public Criteria andMaterialIdGreaterThan(String value) {
			addCriterion("material_id >", value, "materialId");
			return (Criteria) this;
		}

		public Criteria andMaterialIdGreaterThanOrEqualTo(String value) {
			addCriterion("material_id >=", value, "materialId");
			return (Criteria) this;
		}

		public Criteria andMaterialIdLessThan(String value) {
			addCriterion("material_id <", value, "materialId");
			return (Criteria) this;
		}

		public Criteria andMaterialIdLessThanOrEqualTo(String value) {
			addCriterion("material_id <=", value, "materialId");
			return (Criteria) this;
		}

		public Criteria andMaterialIdLike(String value) {
			addCriterion("material_id like", value, "materialId");
			return (Criteria) this;
		}

		public Criteria andMaterialIdNotLike(String value) {
			addCriterion("material_id not like", value, "materialId");
			return (Criteria) this;
		}

		public Criteria andMaterialIdIn(List<String> values) {
			addCriterion("material_id in", values, "materialId");
			return (Criteria) this;
		}

		public Criteria andMaterialIdNotIn(List<String> values) {
			addCriterion("material_id not in", values, "materialId");
			return (Criteria) this;
		}

		public Criteria andMaterialIdBetween(String value1, String value2) {
			addCriterion("material_id between", value1, value2, "materialId");
			return (Criteria) this;
		}

		public Criteria andMaterialIdNotBetween(String value1, String value2) {
			addCriterion("material_id not between", value1, value2, "materialId");
			return (Criteria) this;
		}

		public Criteria andViceIdIsNull() {
			addCriterion("vice_id is null");
			return (Criteria) this;
		}

		public Criteria andViceIdIsNotNull() {
			addCriterion("vice_id is not null");
			return (Criteria) this;
		}

		public Criteria andViceIdEqualTo(String value) {
			addCriterion("vice_id =", value, "viceId");
			return (Criteria) this;
		}

		public Criteria andViceIdNotEqualTo(String value) {
			addCriterion("vice_id <>", value, "viceId");
			return (Criteria) this;
		}

		public Criteria andViceIdGreaterThan(String value) {
			addCriterion("vice_id >", value, "viceId");
			return (Criteria) this;
		}

		public Criteria andViceIdGreaterThanOrEqualTo(String value) {
			addCriterion("vice_id >=", value, "viceId");
			return (Criteria) this;
		}

		public Criteria andViceIdLessThan(String value) {
			addCriterion("vice_id <", value, "viceId");
			return (Criteria) this;
		}

		public Criteria andViceIdLessThanOrEqualTo(String value) {
			addCriterion("vice_id <=", value, "viceId");
			return (Criteria) this;
		}

		public Criteria andViceIdLike(String value) {
			addCriterion("vice_id like", value, "viceId");
			return (Criteria) this;
		}

		public Criteria andViceIdNotLike(String value) {
			addCriterion("vice_id not like", value, "viceId");
			return (Criteria) this;
		}

		public Criteria andViceIdIn(List<String> values) {
			addCriterion("vice_id in", values, "viceId");
			return (Criteria) this;
		}

		public Criteria andViceIdNotIn(List<String> values) {
			addCriterion("vice_id not in", values, "viceId");
			return (Criteria) this;
		}

		public Criteria andViceIdBetween(String value1, String value2) {
			addCriterion("vice_id between", value1, value2, "viceId");
			return (Criteria) this;
		}

		public Criteria andViceIdNotBetween(String value1, String value2) {
			addCriterion("vice_id not between", value1, value2, "viceId");
			return (Criteria) this;
		}

		public Criteria andMaterialNameIsNull() {
			addCriterion("material_name is null");
			return (Criteria) this;
		}

		public Criteria andMaterialNameIsNotNull() {
			addCriterion("material_name is not null");
			return (Criteria) this;
		}

		public Criteria andMaterialNameEqualTo(String value) {
			addCriterion("material_name =", value, "materialName");
			return (Criteria) this;
		}

		public Criteria andMaterialNameNotEqualTo(String value) {
			addCriterion("material_name <>", value, "materialName");
			return (Criteria) this;
		}

		public Criteria andMaterialNameGreaterThan(String value) {
			addCriterion("material_name >", value, "materialName");
			return (Criteria) this;
		}

		public Criteria andMaterialNameGreaterThanOrEqualTo(String value) {
			addCriterion("material_name >=", value, "materialName");
			return (Criteria) this;
		}

		public Criteria andMaterialNameLessThan(String value) {
			addCriterion("material_name <", value, "materialName");
			return (Criteria) this;
		}

		public Criteria andMaterialNameLessThanOrEqualTo(String value) {
			addCriterion("material_name <=", value, "materialName");
			return (Criteria) this;
		}

		public Criteria andMaterialNameLike(String value) {
			addCriterion("material_name like", value, "materialName");
			return (Criteria) this;
		}

		public Criteria andMaterialNameNotLike(String value) {
			addCriterion("material_name not like", value, "materialName");
			return (Criteria) this;
		}

		public Criteria andMaterialNameIn(List<String> values) {
			addCriterion("material_name in", values, "materialName");
			return (Criteria) this;
		}

		public Criteria andMaterialNameNotIn(List<String> values) {
			addCriterion("material_name not in", values, "materialName");
			return (Criteria) this;
		}

		public Criteria andMaterialNameBetween(String value1, String value2) {
			addCriterion("material_name between", value1, value2, "materialName");
			return (Criteria) this;
		}

		public Criteria andMaterialNameNotBetween(String value1, String value2) {
			addCriterion("material_name not between", value1, value2, "materialName");
			return (Criteria) this;
		}

		public Criteria andMaterialSpecIsNull() {
			addCriterion("material_spec is null");
			return (Criteria) this;
		}

		public Criteria andMaterialSpecIsNotNull() {
			addCriterion("material_spec is not null");
			return (Criteria) this;
		}

		public Criteria andMaterialSpecEqualTo(String value) {
			addCriterion("material_spec =", value, "materialSpec");
			return (Criteria) this;
		}

		public Criteria andMaterialSpecNotEqualTo(String value) {
			addCriterion("material_spec <>", value, "materialSpec");
			return (Criteria) this;
		}

		public Criteria andMaterialSpecGreaterThan(String value) {
			addCriterion("material_spec >", value, "materialSpec");
			return (Criteria) this;
		}

		public Criteria andMaterialSpecGreaterThanOrEqualTo(String value) {
			addCriterion("material_spec >=", value, "materialSpec");
			return (Criteria) this;
		}

		public Criteria andMaterialSpecLessThan(String value) {
			addCriterion("material_spec <", value, "materialSpec");
			return (Criteria) this;
		}

		public Criteria andMaterialSpecLessThanOrEqualTo(String value) {
			addCriterion("material_spec <=", value, "materialSpec");
			return (Criteria) this;
		}

		public Criteria andMaterialSpecLike(String value) {
			addCriterion("material_spec like", value, "materialSpec");
			return (Criteria) this;
		}

		public Criteria andMaterialSpecNotLike(String value) {
			addCriterion("material_spec not like", value, "materialSpec");
			return (Criteria) this;
		}

		public Criteria andMaterialSpecIn(List<String> values) {
			addCriterion("material_spec in", values, "materialSpec");
			return (Criteria) this;
		}

		public Criteria andMaterialSpecNotIn(List<String> values) {
			addCriterion("material_spec not in", values, "materialSpec");
			return (Criteria) this;
		}

		public Criteria andMaterialSpecBetween(String value1, String value2) {
			addCriterion("material_spec between", value1, value2, "materialSpec");
			return (Criteria) this;
		}

		public Criteria andMaterialSpecNotBetween(String value1, String value2) {
			addCriterion("material_spec not between", value1, value2, "materialSpec");
			return (Criteria) this;
		}

		public Criteria andWarehousePositionIsNull() {
			addCriterion("warehouse_position is null");
			return (Criteria) this;
		}

		public Criteria andWarehousePositionIsNotNull() {
			addCriterion("warehouse_position is not null");
			return (Criteria) this;
		}

		public Criteria andWarehousePositionEqualTo(String value) {
			addCriterion("warehouse_position =", value, "warehousePosition");
			return (Criteria) this;
		}

		public Criteria andWarehousePositionNotEqualTo(String value) {
			addCriterion("warehouse_position <>", value, "warehousePosition");
			return (Criteria) this;
		}

		public Criteria andWarehousePositionGreaterThan(String value) {
			addCriterion("warehouse_position >", value, "warehousePosition");
			return (Criteria) this;
		}

		public Criteria andWarehousePositionGreaterThanOrEqualTo(String value) {
			addCriterion("warehouse_position >=", value, "warehousePosition");
			return (Criteria) this;
		}

		public Criteria andWarehousePositionLessThan(String value) {
			addCriterion("warehouse_position <", value, "warehousePosition");
			return (Criteria) this;
		}

		public Criteria andWarehousePositionLessThanOrEqualTo(String value) {
			addCriterion("warehouse_position <=", value, "warehousePosition");
			return (Criteria) this;
		}

		public Criteria andWarehousePositionLike(String value) {
			addCriterion("warehouse_position like", value, "warehousePosition");
			return (Criteria) this;
		}

		public Criteria andWarehousePositionNotLike(String value) {
			addCriterion("warehouse_position not like", value, "warehousePosition");
			return (Criteria) this;
		}

		public Criteria andWarehousePositionIn(List<String> values) {
			addCriterion("warehouse_position in", values, "warehousePosition");
			return (Criteria) this;
		}

		public Criteria andWarehousePositionNotIn(List<String> values) {
			addCriterion("warehouse_position not in", values, "warehousePosition");
			return (Criteria) this;
		}

		public Criteria andWarehousePositionBetween(String value1, String value2) {
			addCriterion("warehouse_position between", value1, value2, "warehousePosition");
			return (Criteria) this;
		}

		public Criteria andWarehousePositionNotBetween(String value1, String value2) {
			addCriterion("warehouse_position not between", value1, value2, "warehousePosition");
			return (Criteria) this;
		}

		public Criteria andImportNumberIsNull() {
			addCriterion("import_number is null");
			return (Criteria) this;
		}

		public Criteria andImportNumberIsNotNull() {
			addCriterion("import_number is not null");
			return (Criteria) this;
		}

		public Criteria andImportNumberEqualTo(Integer value) {
			addCriterion("import_number =", value, "importNumber");
			return (Criteria) this;
		}

		public Criteria andImportNumberNotEqualTo(Integer value) {
			addCriterion("import_number <>", value, "importNumber");
			return (Criteria) this;
		}

		public Criteria andImportNumberGreaterThan(Integer value) {
			addCriterion("import_number >", value, "importNumber");
			return (Criteria) this;
		}

		public Criteria andImportNumberGreaterThanOrEqualTo(Integer value) {
			addCriterion("import_number >=", value, "importNumber");
			return (Criteria) this;
		}

		public Criteria andImportNumberLessThan(Integer value) {
			addCriterion("import_number <", value, "importNumber");
			return (Criteria) this;
		}

		public Criteria andImportNumberLessThanOrEqualTo(Integer value) {
			addCriterion("import_number <=", value, "importNumber");
			return (Criteria) this;
		}

		public Criteria andImportNumberIn(List<Integer> values) {
			addCriterion("import_number in", values, "importNumber");
			return (Criteria) this;
		}

		public Criteria andImportNumberNotIn(List<Integer> values) {
			addCriterion("import_number not in", values, "importNumber");
			return (Criteria) this;
		}

		public Criteria andImportNumberBetween(Integer value1, Integer value2) {
			addCriterion("import_number between", value1, value2, "importNumber");
			return (Criteria) this;
		}

		public Criteria andImportNumberNotBetween(Integer value1, Integer value2) {
			addCriterion("import_number not between", value1, value2, "importNumber");
			return (Criteria) this;
		}

		public Criteria andPriceIncludeTaxIsNull() {
			addCriterion("price_include_tax is null");
			return (Criteria) this;
		}

		public Criteria andPriceIncludeTaxIsNotNull() {
			addCriterion("price_include_tax is not null");
			return (Criteria) this;
		}

		public Criteria andPriceIncludeTaxEqualTo(Double value) {
			addCriterion("price_include_tax =", value, "priceIncludeTax");
			return (Criteria) this;
		}

		public Criteria andPriceIncludeTaxNotEqualTo(Double value) {
			addCriterion("price_include_tax <>", value, "priceIncludeTax");
			return (Criteria) this;
		}

		public Criteria andPriceIncludeTaxGreaterThan(Double value) {
			addCriterion("price_include_tax >", value, "priceIncludeTax");
			return (Criteria) this;
		}

		public Criteria andPriceIncludeTaxGreaterThanOrEqualTo(Double value) {
			addCriterion("price_include_tax >=", value, "priceIncludeTax");
			return (Criteria) this;
		}

		public Criteria andPriceIncludeTaxLessThan(Double value) {
			addCriterion("price_include_tax <", value, "priceIncludeTax");
			return (Criteria) this;
		}

		public Criteria andPriceIncludeTaxLessThanOrEqualTo(Double value) {
			addCriterion("price_include_tax <=", value, "priceIncludeTax");
			return (Criteria) this;
		}

		public Criteria andPriceIncludeTaxIn(List<Double> values) {
			addCriterion("price_include_tax in", values, "priceIncludeTax");
			return (Criteria) this;
		}

		public Criteria andPriceIncludeTaxNotIn(List<Double> values) {
			addCriterion("price_include_tax not in", values, "priceIncludeTax");
			return (Criteria) this;
		}

		public Criteria andPriceIncludeTaxBetween(Double value1, Double value2) {
			addCriterion("price_include_tax between", value1, value2, "priceIncludeTax");
			return (Criteria) this;
		}

		public Criteria andPriceIncludeTaxNotBetween(Double value1, Double value2) {
			addCriterion("price_include_tax not between", value1, value2, "priceIncludeTax");
			return (Criteria) this;
		}

		public Criteria andPriceIsNull() {
			addCriterion("price is null");
			return (Criteria) this;
		}

		public Criteria andPriceIsNotNull() {
			addCriterion("price is not null");
			return (Criteria) this;
		}

		public Criteria andPriceEqualTo(Double value) {
			addCriterion("price =", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotEqualTo(Double value) {
			addCriterion("price <>", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceGreaterThan(Double value) {
			addCriterion("price >", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceGreaterThanOrEqualTo(Double value) {
			addCriterion("price >=", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceLessThan(Double value) {
			addCriterion("price <", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceLessThanOrEqualTo(Double value) {
			addCriterion("price <=", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceIn(List<Double> values) {
			addCriterion("price in", values, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotIn(List<Double> values) {
			addCriterion("price not in", values, "price");
			return (Criteria) this;
		}

		public Criteria andPriceBetween(Double value1, Double value2) {
			addCriterion("price between", value1, value2, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotBetween(Double value1, Double value2) {
			addCriterion("price not between", value1, value2, "price");
			return (Criteria) this;
		}

		public Criteria andTaxRateIsNull() {
			addCriterion("tax_rate is null");
			return (Criteria) this;
		}

		public Criteria andTaxRateIsNotNull() {
			addCriterion("tax_rate is not null");
			return (Criteria) this;
		}

		public Criteria andTaxRateEqualTo(Double value) {
			addCriterion("tax_rate =", value, "taxRate");
			return (Criteria) this;
		}

		public Criteria andTaxRateNotEqualTo(Double value) {
			addCriterion("tax_rate <>", value, "taxRate");
			return (Criteria) this;
		}

		public Criteria andTaxRateGreaterThan(Double value) {
			addCriterion("tax_rate >", value, "taxRate");
			return (Criteria) this;
		}

		public Criteria andTaxRateGreaterThanOrEqualTo(Double value) {
			addCriterion("tax_rate >=", value, "taxRate");
			return (Criteria) this;
		}

		public Criteria andTaxRateLessThan(Double value) {
			addCriterion("tax_rate <", value, "taxRate");
			return (Criteria) this;
		}

		public Criteria andTaxRateLessThanOrEqualTo(Double value) {
			addCriterion("tax_rate <=", value, "taxRate");
			return (Criteria) this;
		}

		public Criteria andTaxRateIn(List<Double> values) {
			addCriterion("tax_rate in", values, "taxRate");
			return (Criteria) this;
		}

		public Criteria andTaxRateNotIn(List<Double> values) {
			addCriterion("tax_rate not in", values, "taxRate");
			return (Criteria) this;
		}

		public Criteria andTaxRateBetween(Double value1, Double value2) {
			addCriterion("tax_rate between", value1, value2, "taxRate");
			return (Criteria) this;
		}

		public Criteria andTaxRateNotBetween(Double value1, Double value2) {
			addCriterion("tax_rate not between", value1, value2, "taxRate");
			return (Criteria) this;
		}

		public Criteria andSizeIsNull() {
			addCriterion("size is null");
			return (Criteria) this;
		}

		public Criteria andSizeIsNotNull() {
			addCriterion("size is not null");
			return (Criteria) this;
		}

		public Criteria andSizeEqualTo(String value) {
			addCriterion("size =", value, "size");
			return (Criteria) this;
		}

		public Criteria andSizeNotEqualTo(String value) {
			addCriterion("size <>", value, "size");
			return (Criteria) this;
		}

		public Criteria andSizeGreaterThan(String value) {
			addCriterion("size >", value, "size");
			return (Criteria) this;
		}

		public Criteria andSizeGreaterThanOrEqualTo(String value) {
			addCriterion("size >=", value, "size");
			return (Criteria) this;
		}

		public Criteria andSizeLessThan(String value) {
			addCriterion("size <", value, "size");
			return (Criteria) this;
		}

		public Criteria andSizeLessThanOrEqualTo(String value) {
			addCriterion("size <=", value, "size");
			return (Criteria) this;
		}

		public Criteria andSizeLike(String value) {
			addCriterion("size like", value, "size");
			return (Criteria) this;
		}

		public Criteria andSizeNotLike(String value) {
			addCriterion("size not like", value, "size");
			return (Criteria) this;
		}

		public Criteria andSizeIn(List<String> values) {
			addCriterion("size in", values, "size");
			return (Criteria) this;
		}

		public Criteria andSizeNotIn(List<String> values) {
			addCriterion("size not in", values, "size");
			return (Criteria) this;
		}

		public Criteria andSizeBetween(String value1, String value2) {
			addCriterion("size between", value1, value2, "size");
			return (Criteria) this;
		}

		public Criteria andSizeNotBetween(String value1, String value2) {
			addCriterion("size not between", value1, value2, "size");
			return (Criteria) this;
		}

		public Criteria andTaxIsNull() {
			addCriterion("tax is null");
			return (Criteria) this;
		}

		public Criteria andTaxIsNotNull() {
			addCriterion("tax is not null");
			return (Criteria) this;
		}

		public Criteria andTaxEqualTo(Double value) {
			addCriterion("tax =", value, "tax");
			return (Criteria) this;
		}

		public Criteria andTaxNotEqualTo(Double value) {
			addCriterion("tax <>", value, "tax");
			return (Criteria) this;
		}

		public Criteria andTaxGreaterThan(Double value) {
			addCriterion("tax >", value, "tax");
			return (Criteria) this;
		}

		public Criteria andTaxGreaterThanOrEqualTo(Double value) {
			addCriterion("tax >=", value, "tax");
			return (Criteria) this;
		}

		public Criteria andTaxLessThan(Double value) {
			addCriterion("tax <", value, "tax");
			return (Criteria) this;
		}

		public Criteria andTaxLessThanOrEqualTo(Double value) {
			addCriterion("tax <=", value, "tax");
			return (Criteria) this;
		}

		public Criteria andTaxIn(List<Double> values) {
			addCriterion("tax in", values, "tax");
			return (Criteria) this;
		}

		public Criteria andTaxNotIn(List<Double> values) {
			addCriterion("tax not in", values, "tax");
			return (Criteria) this;
		}

		public Criteria andTaxBetween(Double value1, Double value2) {
			addCriterion("tax between", value1, value2, "tax");
			return (Criteria) this;
		}

		public Criteria andTaxNotBetween(Double value1, Double value2) {
			addCriterion("tax not between", value1, value2, "tax");
			return (Criteria) this;
		}

		public Criteria andTotalPriceIncludeTaxIsNull() {
			addCriterion("total_price_include_tax is null");
			return (Criteria) this;
		}

		public Criteria andTotalPriceIncludeTaxIsNotNull() {
			addCriterion("total_price_include_tax is not null");
			return (Criteria) this;
		}

		public Criteria andTotalPriceIncludeTaxEqualTo(Double value) {
			addCriterion("total_price_include_tax =", value, "totalPriceIncludeTax");
			return (Criteria) this;
		}

		public Criteria andTotalPriceIncludeTaxNotEqualTo(Double value) {
			addCriterion("total_price_include_tax <>", value, "totalPriceIncludeTax");
			return (Criteria) this;
		}

		public Criteria andTotalPriceIncludeTaxGreaterThan(Double value) {
			addCriterion("total_price_include_tax >", value, "totalPriceIncludeTax");
			return (Criteria) this;
		}

		public Criteria andTotalPriceIncludeTaxGreaterThanOrEqualTo(Double value) {
			addCriterion("total_price_include_tax >=", value, "totalPriceIncludeTax");
			return (Criteria) this;
		}

		public Criteria andTotalPriceIncludeTaxLessThan(Double value) {
			addCriterion("total_price_include_tax <", value, "totalPriceIncludeTax");
			return (Criteria) this;
		}

		public Criteria andTotalPriceIncludeTaxLessThanOrEqualTo(Double value) {
			addCriterion("total_price_include_tax <=", value, "totalPriceIncludeTax");
			return (Criteria) this;
		}

		public Criteria andTotalPriceIncludeTaxIn(List<Double> values) {
			addCriterion("total_price_include_tax in", values, "totalPriceIncludeTax");
			return (Criteria) this;
		}

		public Criteria andTotalPriceIncludeTaxNotIn(List<Double> values) {
			addCriterion("total_price_include_tax not in", values, "totalPriceIncludeTax");
			return (Criteria) this;
		}

		public Criteria andTotalPriceIncludeTaxBetween(Double value1, Double value2) {
			addCriterion("total_price_include_tax between", value1, value2, "totalPriceIncludeTax");
			return (Criteria) this;
		}

		public Criteria andTotalPriceIncludeTaxNotBetween(Double value1, Double value2) {
			addCriterion("total_price_include_tax not between", value1, value2, "totalPriceIncludeTax");
			return (Criteria) this;
		}

		public Criteria andTotalPriceIsNull() {
			addCriterion("total_price is null");
			return (Criteria) this;
		}

		public Criteria andTotalPriceIsNotNull() {
			addCriterion("total_price is not null");
			return (Criteria) this;
		}

		public Criteria andTotalPriceEqualTo(Double value) {
			addCriterion("total_price =", value, "totalPrice");
			return (Criteria) this;
		}

		public Criteria andTotalPriceNotEqualTo(Double value) {
			addCriterion("total_price <>", value, "totalPrice");
			return (Criteria) this;
		}

		public Criteria andTotalPriceGreaterThan(Double value) {
			addCriterion("total_price >", value, "totalPrice");
			return (Criteria) this;
		}

		public Criteria andTotalPriceGreaterThanOrEqualTo(Double value) {
			addCriterion("total_price >=", value, "totalPrice");
			return (Criteria) this;
		}

		public Criteria andTotalPriceLessThan(Double value) {
			addCriterion("total_price <", value, "totalPrice");
			return (Criteria) this;
		}

		public Criteria andTotalPriceLessThanOrEqualTo(Double value) {
			addCriterion("total_price <=", value, "totalPrice");
			return (Criteria) this;
		}

		public Criteria andTotalPriceIn(List<Double> values) {
			addCriterion("total_price in", values, "totalPrice");
			return (Criteria) this;
		}

		public Criteria andTotalPriceNotIn(List<Double> values) {
			addCriterion("total_price not in", values, "totalPrice");
			return (Criteria) this;
		}

		public Criteria andTotalPriceBetween(Double value1, Double value2) {
			addCriterion("total_price between", value1, value2, "totalPrice");
			return (Criteria) this;
		}

		public Criteria andTotalPriceNotBetween(Double value1, Double value2) {
			addCriterion("total_price not between", value1, value2, "totalPrice");
			return (Criteria) this;
		}

		public Criteria andUnitIsNull() {
			addCriterion("unit is null");
			return (Criteria) this;
		}

		public Criteria andUnitIsNotNull() {
			addCriterion("unit is not null");
			return (Criteria) this;
		}

		public Criteria andUnitEqualTo(String value) {
			addCriterion("unit =", value, "unit");
			return (Criteria) this;
		}

		public Criteria andUnitNotEqualTo(String value) {
			addCriterion("unit <>", value, "unit");
			return (Criteria) this;
		}

		public Criteria andUnitGreaterThan(String value) {
			addCriterion("unit >", value, "unit");
			return (Criteria) this;
		}

		public Criteria andUnitGreaterThanOrEqualTo(String value) {
			addCriterion("unit >=", value, "unit");
			return (Criteria) this;
		}

		public Criteria andUnitLessThan(String value) {
			addCriterion("unit <", value, "unit");
			return (Criteria) this;
		}

		public Criteria andUnitLessThanOrEqualTo(String value) {
			addCriterion("unit <=", value, "unit");
			return (Criteria) this;
		}

		public Criteria andUnitLike(String value) {
			addCriterion("unit like", value, "unit");
			return (Criteria) this;
		}

		public Criteria andUnitNotLike(String value) {
			addCriterion("unit not like", value, "unit");
			return (Criteria) this;
		}

		public Criteria andUnitIn(List<String> values) {
			addCriterion("unit in", values, "unit");
			return (Criteria) this;
		}

		public Criteria andUnitNotIn(List<String> values) {
			addCriterion("unit not in", values, "unit");
			return (Criteria) this;
		}

		public Criteria andUnitBetween(String value1, String value2) {
			addCriterion("unit between", value1, value2, "unit");
			return (Criteria) this;
		}

		public Criteria andUnitNotBetween(String value1, String value2) {
			addCriterion("unit not between", value1, value2, "unit");
			return (Criteria) this;
		}

		public Criteria andBatchManageIsNull() {
			addCriterion("batch_manage is null");
			return (Criteria) this;
		}

		public Criteria andBatchManageIsNotNull() {
			addCriterion("batch_manage is not null");
			return (Criteria) this;
		}

		public Criteria andBatchManageEqualTo(String value) {
			addCriterion("batch_manage =", value, "batchManage");
			return (Criteria) this;
		}

		public Criteria andBatchManageNotEqualTo(String value) {
			addCriterion("batch_manage <>", value, "batchManage");
			return (Criteria) this;
		}

		public Criteria andBatchManageGreaterThan(String value) {
			addCriterion("batch_manage >", value, "batchManage");
			return (Criteria) this;
		}

		public Criteria andBatchManageGreaterThanOrEqualTo(String value) {
			addCriterion("batch_manage >=", value, "batchManage");
			return (Criteria) this;
		}

		public Criteria andBatchManageLessThan(String value) {
			addCriterion("batch_manage <", value, "batchManage");
			return (Criteria) this;
		}

		public Criteria andBatchManageLessThanOrEqualTo(String value) {
			addCriterion("batch_manage <=", value, "batchManage");
			return (Criteria) this;
		}

		public Criteria andBatchManageLike(String value) {
			addCriterion("batch_manage like", value, "batchManage");
			return (Criteria) this;
		}

		public Criteria andBatchManageNotLike(String value) {
			addCriterion("batch_manage not like", value, "batchManage");
			return (Criteria) this;
		}

		public Criteria andBatchManageIn(List<String> values) {
			addCriterion("batch_manage in", values, "batchManage");
			return (Criteria) this;
		}

		public Criteria andBatchManageNotIn(List<String> values) {
			addCriterion("batch_manage not in", values, "batchManage");
			return (Criteria) this;
		}

		public Criteria andBatchManageBetween(String value1, String value2) {
			addCriterion("batch_manage between", value1, value2, "batchManage");
			return (Criteria) this;
		}

		public Criteria andBatchManageNotBetween(String value1, String value2) {
			addCriterion("batch_manage not between", value1, value2, "batchManage");
			return (Criteria) this;
		}

		public Criteria andSupplierIsNull() {
			addCriterion("supplier is null");
			return (Criteria) this;
		}

		public Criteria andSupplierIsNotNull() {
			addCriterion("supplier is not null");
			return (Criteria) this;
		}

		public Criteria andSupplierEqualTo(String value) {
			addCriterion("supplier =", value, "supplier");
			return (Criteria) this;
		}

		public Criteria andSupplierNotEqualTo(String value) {
			addCriterion("supplier <>", value, "supplier");
			return (Criteria) this;
		}

		public Criteria andSupplierGreaterThan(String value) {
			addCriterion("supplier >", value, "supplier");
			return (Criteria) this;
		}

		public Criteria andSupplierGreaterThanOrEqualTo(String value) {
			addCriterion("supplier >=", value, "supplier");
			return (Criteria) this;
		}

		public Criteria andSupplierLessThan(String value) {
			addCriterion("supplier <", value, "supplier");
			return (Criteria) this;
		}

		public Criteria andSupplierLessThanOrEqualTo(String value) {
			addCriterion("supplier <=", value, "supplier");
			return (Criteria) this;
		}

		public Criteria andSupplierLike(String value) {
			addCriterion("supplier like", value, "supplier");
			return (Criteria) this;
		}

		public Criteria andSupplierNotLike(String value) {
			addCriterion("supplier not like", value, "supplier");
			return (Criteria) this;
		}

		public Criteria andSupplierIn(List<String> values) {
			addCriterion("supplier in", values, "supplier");
			return (Criteria) this;
		}

		public Criteria andSupplierNotIn(List<String> values) {
			addCriterion("supplier not in", values, "supplier");
			return (Criteria) this;
		}

		public Criteria andSupplierBetween(String value1, String value2) {
			addCriterion("supplier between", value1, value2, "supplier");
			return (Criteria) this;
		}

		public Criteria andSupplierNotBetween(String value1, String value2) {
			addCriterion("supplier not between", value1, value2, "supplier");
			return (Criteria) this;
		}

		public Criteria andManufacturingIsNull() {
			addCriterion("manufacturing is null");
			return (Criteria) this;
		}

		public Criteria andManufacturingIsNotNull() {
			addCriterion("manufacturing is not null");
			return (Criteria) this;
		}

		public Criteria andManufacturingEqualTo(String value) {
			addCriterion("manufacturing =", value, "manufacturing");
			return (Criteria) this;
		}

		public Criteria andManufacturingNotEqualTo(String value) {
			addCriterion("manufacturing <>", value, "manufacturing");
			return (Criteria) this;
		}

		public Criteria andManufacturingGreaterThan(String value) {
			addCriterion("manufacturing >", value, "manufacturing");
			return (Criteria) this;
		}

		public Criteria andManufacturingGreaterThanOrEqualTo(String value) {
			addCriterion("manufacturing >=", value, "manufacturing");
			return (Criteria) this;
		}

		public Criteria andManufacturingLessThan(String value) {
			addCriterion("manufacturing <", value, "manufacturing");
			return (Criteria) this;
		}

		public Criteria andManufacturingLessThanOrEqualTo(String value) {
			addCriterion("manufacturing <=", value, "manufacturing");
			return (Criteria) this;
		}

		public Criteria andManufacturingLike(String value) {
			addCriterion("manufacturing like", value, "manufacturing");
			return (Criteria) this;
		}

		public Criteria andManufacturingNotLike(String value) {
			addCriterion("manufacturing not like", value, "manufacturing");
			return (Criteria) this;
		}

		public Criteria andManufacturingIn(List<String> values) {
			addCriterion("manufacturing in", values, "manufacturing");
			return (Criteria) this;
		}

		public Criteria andManufacturingNotIn(List<String> values) {
			addCriterion("manufacturing not in", values, "manufacturing");
			return (Criteria) this;
		}

		public Criteria andManufacturingBetween(String value1, String value2) {
			addCriterion("manufacturing between", value1, value2, "manufacturing");
			return (Criteria) this;
		}

		public Criteria andManufacturingNotBetween(String value1, String value2) {
			addCriterion("manufacturing not between", value1, value2, "manufacturing");
			return (Criteria) this;
		}

		public Criteria andPlusIsNull() {
			addCriterion("plus is null");
			return (Criteria) this;
		}

		public Criteria andPlusIsNotNull() {
			addCriterion("plus is not null");
			return (Criteria) this;
		}

		public Criteria andPlusEqualTo(String value) {
			addCriterion("plus =", value, "plus");
			return (Criteria) this;
		}

		public Criteria andPlusNotEqualTo(String value) {
			addCriterion("plus <>", value, "plus");
			return (Criteria) this;
		}

		public Criteria andPlusGreaterThan(String value) {
			addCriterion("plus >", value, "plus");
			return (Criteria) this;
		}

		public Criteria andPlusGreaterThanOrEqualTo(String value) {
			addCriterion("plus >=", value, "plus");
			return (Criteria) this;
		}

		public Criteria andPlusLessThan(String value) {
			addCriterion("plus <", value, "plus");
			return (Criteria) this;
		}

		public Criteria andPlusLessThanOrEqualTo(String value) {
			addCriterion("plus <=", value, "plus");
			return (Criteria) this;
		}

		public Criteria andPlusLike(String value) {
			addCriterion("plus like", value, "plus");
			return (Criteria) this;
		}

		public Criteria andPlusNotLike(String value) {
			addCriterion("plus not like", value, "plus");
			return (Criteria) this;
		}

		public Criteria andPlusIn(List<String> values) {
			addCriterion("plus in", values, "plus");
			return (Criteria) this;
		}

		public Criteria andPlusNotIn(List<String> values) {
			addCriterion("plus not in", values, "plus");
			return (Criteria) this;
		}

		public Criteria andPlusBetween(String value1, String value2) {
			addCriterion("plus between", value1, value2, "plus");
			return (Criteria) this;
		}

		public Criteria andPlusNotBetween(String value1, String value2) {
			addCriterion("plus not between", value1, value2, "plus");
			return (Criteria) this;
		}

		public Criteria andXinyiInportcolIsNull() {
			addCriterion("xinyi_inportcol is null");
			return (Criteria) this;
		}

		public Criteria andXinyiInportcolIsNotNull() {
			addCriterion("xinyi_inportcol is not null");
			return (Criteria) this;
		}

		public Criteria andXinyiInportcolEqualTo(String value) {
			addCriterion("xinyi_inportcol =", value, "xinyiInportcol");
			return (Criteria) this;
		}

		public Criteria andXinyiInportcolNotEqualTo(String value) {
			addCriterion("xinyi_inportcol <>", value, "xinyiInportcol");
			return (Criteria) this;
		}

		public Criteria andXinyiInportcolGreaterThan(String value) {
			addCriterion("xinyi_inportcol >", value, "xinyiInportcol");
			return (Criteria) this;
		}

		public Criteria andXinyiInportcolGreaterThanOrEqualTo(String value) {
			addCriterion("xinyi_inportcol >=", value, "xinyiInportcol");
			return (Criteria) this;
		}

		public Criteria andXinyiInportcolLessThan(String value) {
			addCriterion("xinyi_inportcol <", value, "xinyiInportcol");
			return (Criteria) this;
		}

		public Criteria andXinyiInportcolLessThanOrEqualTo(String value) {
			addCriterion("xinyi_inportcol <=", value, "xinyiInportcol");
			return (Criteria) this;
		}

		public Criteria andXinyiInportcolLike(String value) {
			addCriterion("xinyi_inportcol like", value, "xinyiInportcol");
			return (Criteria) this;
		}

		public Criteria andXinyiInportcolNotLike(String value) {
			addCriterion("xinyi_inportcol not like", value, "xinyiInportcol");
			return (Criteria) this;
		}

		public Criteria andXinyiInportcolIn(List<String> values) {
			addCriterion("xinyi_inportcol in", values, "xinyiInportcol");
			return (Criteria) this;
		}

		public Criteria andXinyiInportcolNotIn(List<String> values) {
			addCriterion("xinyi_inportcol not in", values, "xinyiInportcol");
			return (Criteria) this;
		}

		public Criteria andXinyiInportcolBetween(String value1, String value2) {
			addCriterion("xinyi_inportcol between", value1, value2, "xinyiInportcol");
			return (Criteria) this;
		}

		public Criteria andXinyiInportcolNotBetween(String value1, String value2) {
			addCriterion("xinyi_inportcol not between", value1, value2, "xinyiInportcol");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table xinyi_import
	 * @mbg.generated  Sat Jul 27 13:57:14 CST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table xinyi_import
     *
     * @mbg.generated do_not_delete_during_merge Sat Jul 27 13:22:46 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}