package com.xinyi.bean;

import java.util.Date;

public class XinyiMaterial {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_material.material_id
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	private String materialId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_material.vice_id
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	private String viceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_material.material_name
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	private String materialName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_material.material_spec
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	private String materialSpec;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_material.warehouse_position
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	private String warehousePosition;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_material.plus
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	private String plus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_material.material_type
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	private String materialType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_material.material_unit
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	private String materialUnit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_material.material_price
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	private Float materialPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_material.stock_number
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	private Integer stockNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_material.stock_safe
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	private Integer stockSafe;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_material.batch_manage
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	private String batchManage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_material.finance
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	private String finance;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_material.status
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_material.finish_time
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	private Date finishTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_material.start_time
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	private Date startTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_material.create_manager
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	private String createManager;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_material.change_time
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	private Date changeTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_material.change_manager
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	private String changeManager;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_material.material_id
	 * @return  the value of xinyi_material.material_id
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	public String getMaterialId() {
		return materialId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_material.material_id
	 * @param materialId  the value for xinyi_material.material_id
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	public void setMaterialId(String materialId) {
		this.materialId = materialId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_material.vice_id
	 * @return  the value of xinyi_material.vice_id
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	public String getViceId() {
		return viceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_material.vice_id
	 * @param viceId  the value for xinyi_material.vice_id
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	public void setViceId(String viceId) {
		this.viceId = viceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_material.material_name
	 * @return  the value of xinyi_material.material_name
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	public String getMaterialName() {
		return materialName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_material.material_name
	 * @param materialName  the value for xinyi_material.material_name
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	public void setMaterialName(String materialName) {
		this.materialName = materialName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_material.material_spec
	 * @return  the value of xinyi_material.material_spec
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	public String getMaterialSpec() {
		return materialSpec;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_material.material_spec
	 * @param materialSpec  the value for xinyi_material.material_spec
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	public void setMaterialSpec(String materialSpec) {
		this.materialSpec = materialSpec;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_material.warehouse_position
	 * @return  the value of xinyi_material.warehouse_position
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	public String getWarehousePosition() {
		return warehousePosition;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_material.warehouse_position
	 * @param warehousePosition  the value for xinyi_material.warehouse_position
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	public void setWarehousePosition(String warehousePosition) {
		this.warehousePosition = warehousePosition;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_material.plus
	 * @return  the value of xinyi_material.plus
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	public String getPlus() {
		return plus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_material.plus
	 * @param plus  the value for xinyi_material.plus
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	public void setPlus(String plus) {
		this.plus = plus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_material.material_type
	 * @return  the value of xinyi_material.material_type
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	public String getMaterialType() {
		return materialType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_material.material_type
	 * @param materialType  the value for xinyi_material.material_type
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	public void setMaterialType(String materialType) {
		this.materialType = materialType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_material.material_unit
	 * @return  the value of xinyi_material.material_unit
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	public String getMaterialUnit() {
		return materialUnit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_material.material_unit
	 * @param materialUnit  the value for xinyi_material.material_unit
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	public void setMaterialUnit(String materialUnit) {
		this.materialUnit = materialUnit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_material.material_price
	 * @return  the value of xinyi_material.material_price
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	public Float getMaterialPrice() {
		return materialPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_material.material_price
	 * @param materialPrice  the value for xinyi_material.material_price
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	public void setMaterialPrice(Float materialPrice) {
		this.materialPrice = materialPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_material.stock_number
	 * @return  the value of xinyi_material.stock_number
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	public Integer getStockNumber() {
		return stockNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_material.stock_number
	 * @param stockNumber  the value for xinyi_material.stock_number
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	public void setStockNumber(Integer stockNumber) {
		this.stockNumber = stockNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_material.stock_safe
	 * @return  the value of xinyi_material.stock_safe
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	public Integer getStockSafe() {
		return stockSafe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_material.stock_safe
	 * @param stockSafe  the value for xinyi_material.stock_safe
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	public void setStockSafe(Integer stockSafe) {
		this.stockSafe = stockSafe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_material.batch_manage
	 * @return  the value of xinyi_material.batch_manage
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	public String getBatchManage() {
		return batchManage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_material.batch_manage
	 * @param batchManage  the value for xinyi_material.batch_manage
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	public void setBatchManage(String batchManage) {
		this.batchManage = batchManage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_material.finance
	 * @return  the value of xinyi_material.finance
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	public String getFinance() {
		return finance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_material.finance
	 * @param finance  the value for xinyi_material.finance
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	public void setFinance(String finance) {
		this.finance = finance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_material.status
	 * @return  the value of xinyi_material.status
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_material.status
	 * @param status  the value for xinyi_material.status
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_material.finish_time
	 * @return  the value of xinyi_material.finish_time
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	public Date getFinishTime() {
		return finishTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_material.finish_time
	 * @param finishTime  the value for xinyi_material.finish_time
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	public void setFinishTime(Date finishTime) {
		this.finishTime = finishTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_material.start_time
	 * @return  the value of xinyi_material.start_time
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	public Date getStartTime() {
		return startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_material.start_time
	 * @param startTime  the value for xinyi_material.start_time
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_material.create_manager
	 * @return  the value of xinyi_material.create_manager
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	public String getCreateManager() {
		return createManager;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_material.create_manager
	 * @param createManager  the value for xinyi_material.create_manager
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	public void setCreateManager(String createManager) {
		this.createManager = createManager;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_material.change_time
	 * @return  the value of xinyi_material.change_time
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	public Date getChangeTime() {
		return changeTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_material.change_time
	 * @param changeTime  the value for xinyi_material.change_time
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	public void setChangeTime(Date changeTime) {
		this.changeTime = changeTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_material.change_manager
	 * @return  the value of xinyi_material.change_manager
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	public String getChangeManager() {
		return changeManager;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_material.change_manager
	 * @param changeManager  the value for xinyi_material.change_manager
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	public void setChangeManager(String changeManager) {
		this.changeManager = changeManager;
	}
}