package com.xinyi.bean;

import java.util.ArrayList;
import java.util.List;

public class XinyiBatchStockExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table xinyi_batch_stock
	 * @mbg.generated  Tue Aug 06 10:30:46 CST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table xinyi_batch_stock
	 * @mbg.generated  Tue Aug 06 10:30:46 CST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table xinyi_batch_stock
	 * @mbg.generated  Tue Aug 06 10:30:46 CST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_batch_stock
	 * @mbg.generated  Tue Aug 06 10:30:46 CST 2019
	 */
	public XinyiBatchStockExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_batch_stock
	 * @mbg.generated  Tue Aug 06 10:30:46 CST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_batch_stock
	 * @mbg.generated  Tue Aug 06 10:30:46 CST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_batch_stock
	 * @mbg.generated  Tue Aug 06 10:30:46 CST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_batch_stock
	 * @mbg.generated  Tue Aug 06 10:30:46 CST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_batch_stock
	 * @mbg.generated  Tue Aug 06 10:30:46 CST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_batch_stock
	 * @mbg.generated  Tue Aug 06 10:30:46 CST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_batch_stock
	 * @mbg.generated  Tue Aug 06 10:30:46 CST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_batch_stock
	 * @mbg.generated  Tue Aug 06 10:30:46 CST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_batch_stock
	 * @mbg.generated  Tue Aug 06 10:30:46 CST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_batch_stock
	 * @mbg.generated  Tue Aug 06 10:30:46 CST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table xinyi_batch_stock
	 * @mbg.generated  Tue Aug 06 10:30:46 CST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andBatchIsNull() {
			addCriterion("batch is null");
			return (Criteria) this;
		}

		public Criteria andBatchIsNotNull() {
			addCriterion("batch is not null");
			return (Criteria) this;
		}

		public Criteria andBatchEqualTo(String value) {
			addCriterion("batch =", value, "batch");
			return (Criteria) this;
		}

		public Criteria andBatchNotEqualTo(String value) {
			addCriterion("batch <>", value, "batch");
			return (Criteria) this;
		}

		public Criteria andBatchGreaterThan(String value) {
			addCriterion("batch >", value, "batch");
			return (Criteria) this;
		}

		public Criteria andBatchGreaterThanOrEqualTo(String value) {
			addCriterion("batch >=", value, "batch");
			return (Criteria) this;
		}

		public Criteria andBatchLessThan(String value) {
			addCriterion("batch <", value, "batch");
			return (Criteria) this;
		}

		public Criteria andBatchLessThanOrEqualTo(String value) {
			addCriterion("batch <=", value, "batch");
			return (Criteria) this;
		}

		public Criteria andBatchLike(String value) {
			addCriterion("batch like", value, "batch");
			return (Criteria) this;
		}

		public Criteria andBatchNotLike(String value) {
			addCriterion("batch not like", value, "batch");
			return (Criteria) this;
		}

		public Criteria andBatchIn(List<String> values) {
			addCriterion("batch in", values, "batch");
			return (Criteria) this;
		}

		public Criteria andBatchNotIn(List<String> values) {
			addCriterion("batch not in", values, "batch");
			return (Criteria) this;
		}

		public Criteria andBatchBetween(String value1, String value2) {
			addCriterion("batch between", value1, value2, "batch");
			return (Criteria) this;
		}

		public Criteria andBatchNotBetween(String value1, String value2) {
			addCriterion("batch not between", value1, value2, "batch");
			return (Criteria) this;
		}

		public Criteria andNumberIsNull() {
			addCriterion("number is null");
			return (Criteria) this;
		}

		public Criteria andNumberIsNotNull() {
			addCriterion("number is not null");
			return (Criteria) this;
		}

		public Criteria andNumberEqualTo(Integer value) {
			addCriterion("number =", value, "number");
			return (Criteria) this;
		}

		public Criteria andNumberNotEqualTo(Integer value) {
			addCriterion("number <>", value, "number");
			return (Criteria) this;
		}

		public Criteria andNumberGreaterThan(Integer value) {
			addCriterion("number >", value, "number");
			return (Criteria) this;
		}

		public Criteria andNumberGreaterThanOrEqualTo(Integer value) {
			addCriterion("number >=", value, "number");
			return (Criteria) this;
		}

		public Criteria andNumberLessThan(Integer value) {
			addCriterion("number <", value, "number");
			return (Criteria) this;
		}

		public Criteria andNumberLessThanOrEqualTo(Integer value) {
			addCriterion("number <=", value, "number");
			return (Criteria) this;
		}

		public Criteria andNumberIn(List<Integer> values) {
			addCriterion("number in", values, "number");
			return (Criteria) this;
		}

		public Criteria andNumberNotIn(List<Integer> values) {
			addCriterion("number not in", values, "number");
			return (Criteria) this;
		}

		public Criteria andNumberBetween(Integer value1, Integer value2) {
			addCriterion("number between", value1, value2, "number");
			return (Criteria) this;
		}

		public Criteria andNumberNotBetween(Integer value1, Integer value2) {
			addCriterion("number not between", value1, value2, "number");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andPriceIsNull() {
			addCriterion("price is null");
			return (Criteria) this;
		}

		public Criteria andPriceIsNotNull() {
			addCriterion("price is not null");
			return (Criteria) this;
		}

		public Criteria andPriceEqualTo(Double value) {
			addCriterion("price =", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotEqualTo(Double value) {
			addCriterion("price <>", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceGreaterThan(Double value) {
			addCriterion("price >", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceGreaterThanOrEqualTo(Double value) {
			addCriterion("price >=", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceLessThan(Double value) {
			addCriterion("price <", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceLessThanOrEqualTo(Double value) {
			addCriterion("price <=", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceIn(List<Double> values) {
			addCriterion("price in", values, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotIn(List<Double> values) {
			addCriterion("price not in", values, "price");
			return (Criteria) this;
		}

		public Criteria andPriceBetween(Double value1, Double value2) {
			addCriterion("price between", value1, value2, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotBetween(Double value1, Double value2) {
			addCriterion("price not between", value1, value2, "price");
			return (Criteria) this;
		}

		public Criteria andPlusIsNull() {
			addCriterion("plus is null");
			return (Criteria) this;
		}

		public Criteria andPlusIsNotNull() {
			addCriterion("plus is not null");
			return (Criteria) this;
		}

		public Criteria andPlusEqualTo(String value) {
			addCriterion("plus =", value, "plus");
			return (Criteria) this;
		}

		public Criteria andPlusNotEqualTo(String value) {
			addCriterion("plus <>", value, "plus");
			return (Criteria) this;
		}

		public Criteria andPlusGreaterThan(String value) {
			addCriterion("plus >", value, "plus");
			return (Criteria) this;
		}

		public Criteria andPlusGreaterThanOrEqualTo(String value) {
			addCriterion("plus >=", value, "plus");
			return (Criteria) this;
		}

		public Criteria andPlusLessThan(String value) {
			addCriterion("plus <", value, "plus");
			return (Criteria) this;
		}

		public Criteria andPlusLessThanOrEqualTo(String value) {
			addCriterion("plus <=", value, "plus");
			return (Criteria) this;
		}

		public Criteria andPlusLike(String value) {
			addCriterion("plus like", value, "plus");
			return (Criteria) this;
		}

		public Criteria andPlusNotLike(String value) {
			addCriterion("plus not like", value, "plus");
			return (Criteria) this;
		}

		public Criteria andPlusIn(List<String> values) {
			addCriterion("plus in", values, "plus");
			return (Criteria) this;
		}

		public Criteria andPlusNotIn(List<String> values) {
			addCriterion("plus not in", values, "plus");
			return (Criteria) this;
		}

		public Criteria andPlusBetween(String value1, String value2) {
			addCriterion("plus between", value1, value2, "plus");
			return (Criteria) this;
		}

		public Criteria andPlusNotBetween(String value1, String value2) {
			addCriterion("plus not between", value1, value2, "plus");
			return (Criteria) this;
		}

		public Criteria andMaterialidIsNull() {
			addCriterion("materialId is null");
			return (Criteria) this;
		}

		public Criteria andMaterialidIsNotNull() {
			addCriterion("materialId is not null");
			return (Criteria) this;
		}

		public Criteria andMaterialidEqualTo(String value) {
			addCriterion("materialId =", value, "materialid");
			return (Criteria) this;
		}

		public Criteria andMaterialidNotEqualTo(String value) {
			addCriterion("materialId <>", value, "materialid");
			return (Criteria) this;
		}

		public Criteria andMaterialidGreaterThan(String value) {
			addCriterion("materialId >", value, "materialid");
			return (Criteria) this;
		}

		public Criteria andMaterialidGreaterThanOrEqualTo(String value) {
			addCriterion("materialId >=", value, "materialid");
			return (Criteria) this;
		}

		public Criteria andMaterialidLessThan(String value) {
			addCriterion("materialId <", value, "materialid");
			return (Criteria) this;
		}

		public Criteria andMaterialidLessThanOrEqualTo(String value) {
			addCriterion("materialId <=", value, "materialid");
			return (Criteria) this;
		}

		public Criteria andMaterialidLike(String value) {
			addCriterion("materialId like", value, "materialid");
			return (Criteria) this;
		}

		public Criteria andMaterialidNotLike(String value) {
			addCriterion("materialId not like", value, "materialid");
			return (Criteria) this;
		}

		public Criteria andMaterialidIn(List<String> values) {
			addCriterion("materialId in", values, "materialid");
			return (Criteria) this;
		}

		public Criteria andMaterialidNotIn(List<String> values) {
			addCriterion("materialId not in", values, "materialid");
			return (Criteria) this;
		}

		public Criteria andMaterialidBetween(String value1, String value2) {
			addCriterion("materialId between", value1, value2, "materialid");
			return (Criteria) this;
		}

		public Criteria andMaterialidNotBetween(String value1, String value2) {
			addCriterion("materialId not between", value1, value2, "materialid");
			return (Criteria) this;
		}

		public Criteria andManufacturerIsNull() {
			addCriterion("manufacturer is null");
			return (Criteria) this;
		}

		public Criteria andManufacturerIsNotNull() {
			addCriterion("manufacturer is not null");
			return (Criteria) this;
		}

		public Criteria andManufacturerEqualTo(String value) {
			addCriterion("manufacturer =", value, "manufacturer");
			return (Criteria) this;
		}

		public Criteria andManufacturerNotEqualTo(String value) {
			addCriterion("manufacturer <>", value, "manufacturer");
			return (Criteria) this;
		}

		public Criteria andManufacturerGreaterThan(String value) {
			addCriterion("manufacturer >", value, "manufacturer");
			return (Criteria) this;
		}

		public Criteria andManufacturerGreaterThanOrEqualTo(String value) {
			addCriterion("manufacturer >=", value, "manufacturer");
			return (Criteria) this;
		}

		public Criteria andManufacturerLessThan(String value) {
			addCriterion("manufacturer <", value, "manufacturer");
			return (Criteria) this;
		}

		public Criteria andManufacturerLessThanOrEqualTo(String value) {
			addCriterion("manufacturer <=", value, "manufacturer");
			return (Criteria) this;
		}

		public Criteria andManufacturerLike(String value) {
			addCriterion("manufacturer like", value, "manufacturer");
			return (Criteria) this;
		}

		public Criteria andManufacturerNotLike(String value) {
			addCriterion("manufacturer not like", value, "manufacturer");
			return (Criteria) this;
		}

		public Criteria andManufacturerIn(List<String> values) {
			addCriterion("manufacturer in", values, "manufacturer");
			return (Criteria) this;
		}

		public Criteria andManufacturerNotIn(List<String> values) {
			addCriterion("manufacturer not in", values, "manufacturer");
			return (Criteria) this;
		}

		public Criteria andManufacturerBetween(String value1, String value2) {
			addCriterion("manufacturer between", value1, value2, "manufacturer");
			return (Criteria) this;
		}

		public Criteria andManufacturerNotBetween(String value1, String value2) {
			addCriterion("manufacturer not between", value1, value2, "manufacturer");
			return (Criteria) this;
		}

		public Criteria andSupplierIsNull() {
			addCriterion("supplier is null");
			return (Criteria) this;
		}

		public Criteria andSupplierIsNotNull() {
			addCriterion("supplier is not null");
			return (Criteria) this;
		}

		public Criteria andSupplierEqualTo(String value) {
			addCriterion("supplier =", value, "supplier");
			return (Criteria) this;
		}

		public Criteria andSupplierNotEqualTo(String value) {
			addCriterion("supplier <>", value, "supplier");
			return (Criteria) this;
		}

		public Criteria andSupplierGreaterThan(String value) {
			addCriterion("supplier >", value, "supplier");
			return (Criteria) this;
		}

		public Criteria andSupplierGreaterThanOrEqualTo(String value) {
			addCriterion("supplier >=", value, "supplier");
			return (Criteria) this;
		}

		public Criteria andSupplierLessThan(String value) {
			addCriterion("supplier <", value, "supplier");
			return (Criteria) this;
		}

		public Criteria andSupplierLessThanOrEqualTo(String value) {
			addCriterion("supplier <=", value, "supplier");
			return (Criteria) this;
		}

		public Criteria andSupplierLike(String value) {
			addCriterion("supplier like", value, "supplier");
			return (Criteria) this;
		}

		public Criteria andSupplierNotLike(String value) {
			addCriterion("supplier not like", value, "supplier");
			return (Criteria) this;
		}

		public Criteria andSupplierIn(List<String> values) {
			addCriterion("supplier in", values, "supplier");
			return (Criteria) this;
		}

		public Criteria andSupplierNotIn(List<String> values) {
			addCriterion("supplier not in", values, "supplier");
			return (Criteria) this;
		}

		public Criteria andSupplierBetween(String value1, String value2) {
			addCriterion("supplier between", value1, value2, "supplier");
			return (Criteria) this;
		}

		public Criteria andSupplierNotBetween(String value1, String value2) {
			addCriterion("supplier not between", value1, value2, "supplier");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table xinyi_batch_stock
	 * @mbg.generated  Tue Aug 06 10:30:46 CST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table xinyi_batch_stock
     *
     * @mbg.generated do_not_delete_during_merge Thu Aug 01 10:15:47 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}