package com.xinyi.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class XinyiMaterialExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table xinyi_material
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table xinyi_material
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table xinyi_material
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_material
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	public XinyiMaterialExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_material
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_material
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_material
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_material
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_material
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_material
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_material
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_material
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_material
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_material
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table xinyi_material
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andMaterialIdIsNull() {
			addCriterion("material_id is null");
			return (Criteria) this;
		}

		public Criteria andMaterialIdIsNotNull() {
			addCriterion("material_id is not null");
			return (Criteria) this;
		}

		public Criteria andMaterialIdEqualTo(String value) {
			addCriterion("material_id =", value, "materialId");
			return (Criteria) this;
		}

		public Criteria andMaterialIdNotEqualTo(String value) {
			addCriterion("material_id <>", value, "materialId");
			return (Criteria) this;
		}

		public Criteria andMaterialIdGreaterThan(String value) {
			addCriterion("material_id >", value, "materialId");
			return (Criteria) this;
		}

		public Criteria andMaterialIdGreaterThanOrEqualTo(String value) {
			addCriterion("material_id >=", value, "materialId");
			return (Criteria) this;
		}

		public Criteria andMaterialIdLessThan(String value) {
			addCriterion("material_id <", value, "materialId");
			return (Criteria) this;
		}

		public Criteria andMaterialIdLessThanOrEqualTo(String value) {
			addCriterion("material_id <=", value, "materialId");
			return (Criteria) this;
		}

		public Criteria andMaterialIdLike(String value) {
			addCriterion("material_id like", value, "materialId");
			return (Criteria) this;
		}

		public Criteria andMaterialIdNotLike(String value) {
			addCriterion("material_id not like", value, "materialId");
			return (Criteria) this;
		}

		public Criteria andMaterialIdIn(List<String> values) {
			addCriterion("material_id in", values, "materialId");
			return (Criteria) this;
		}

		public Criteria andMaterialIdNotIn(List<String> values) {
			addCriterion("material_id not in", values, "materialId");
			return (Criteria) this;
		}

		public Criteria andMaterialIdBetween(String value1, String value2) {
			addCriterion("material_id between", value1, value2, "materialId");
			return (Criteria) this;
		}

		public Criteria andMaterialIdNotBetween(String value1, String value2) {
			addCriterion("material_id not between", value1, value2, "materialId");
			return (Criteria) this;
		}

		public Criteria andViceIdIsNull() {
			addCriterion("vice_id is null");
			return (Criteria) this;
		}

		public Criteria andViceIdIsNotNull() {
			addCriterion("vice_id is not null");
			return (Criteria) this;
		}

		public Criteria andViceIdEqualTo(String value) {
			addCriterion("vice_id =", value, "viceId");
			return (Criteria) this;
		}

		public Criteria andViceIdNotEqualTo(String value) {
			addCriterion("vice_id <>", value, "viceId");
			return (Criteria) this;
		}

		public Criteria andViceIdGreaterThan(String value) {
			addCriterion("vice_id >", value, "viceId");
			return (Criteria) this;
		}

		public Criteria andViceIdGreaterThanOrEqualTo(String value) {
			addCriterion("vice_id >=", value, "viceId");
			return (Criteria) this;
		}

		public Criteria andViceIdLessThan(String value) {
			addCriterion("vice_id <", value, "viceId");
			return (Criteria) this;
		}

		public Criteria andViceIdLessThanOrEqualTo(String value) {
			addCriterion("vice_id <=", value, "viceId");
			return (Criteria) this;
		}

		public Criteria andViceIdLike(String value) {
			addCriterion("vice_id like", value, "viceId");
			return (Criteria) this;
		}

		public Criteria andViceIdNotLike(String value) {
			addCriterion("vice_id not like", value, "viceId");
			return (Criteria) this;
		}

		public Criteria andViceIdIn(List<String> values) {
			addCriterion("vice_id in", values, "viceId");
			return (Criteria) this;
		}

		public Criteria andViceIdNotIn(List<String> values) {
			addCriterion("vice_id not in", values, "viceId");
			return (Criteria) this;
		}

		public Criteria andViceIdBetween(String value1, String value2) {
			addCriterion("vice_id between", value1, value2, "viceId");
			return (Criteria) this;
		}

		public Criteria andViceIdNotBetween(String value1, String value2) {
			addCriterion("vice_id not between", value1, value2, "viceId");
			return (Criteria) this;
		}

		public Criteria andMaterialNameIsNull() {
			addCriterion("material_name is null");
			return (Criteria) this;
		}

		public Criteria andMaterialNameIsNotNull() {
			addCriterion("material_name is not null");
			return (Criteria) this;
		}

		public Criteria andMaterialNameEqualTo(String value) {
			addCriterion("material_name =", value, "materialName");
			return (Criteria) this;
		}

		public Criteria andMaterialNameNotEqualTo(String value) {
			addCriterion("material_name <>", value, "materialName");
			return (Criteria) this;
		}

		public Criteria andMaterialNameGreaterThan(String value) {
			addCriterion("material_name >", value, "materialName");
			return (Criteria) this;
		}

		public Criteria andMaterialNameGreaterThanOrEqualTo(String value) {
			addCriterion("material_name >=", value, "materialName");
			return (Criteria) this;
		}

		public Criteria andMaterialNameLessThan(String value) {
			addCriterion("material_name <", value, "materialName");
			return (Criteria) this;
		}

		public Criteria andMaterialNameLessThanOrEqualTo(String value) {
			addCriterion("material_name <=", value, "materialName");
			return (Criteria) this;
		}

		public Criteria andMaterialNameLike(String value) {
			addCriterion("material_name like", value, "materialName");
			return (Criteria) this;
		}

		public Criteria andMaterialNameNotLike(String value) {
			addCriterion("material_name not like", value, "materialName");
			return (Criteria) this;
		}

		public Criteria andMaterialNameIn(List<String> values) {
			addCriterion("material_name in", values, "materialName");
			return (Criteria) this;
		}

		public Criteria andMaterialNameNotIn(List<String> values) {
			addCriterion("material_name not in", values, "materialName");
			return (Criteria) this;
		}

		public Criteria andMaterialNameBetween(String value1, String value2) {
			addCriterion("material_name between", value1, value2, "materialName");
			return (Criteria) this;
		}

		public Criteria andMaterialNameNotBetween(String value1, String value2) {
			addCriterion("material_name not between", value1, value2, "materialName");
			return (Criteria) this;
		}

		public Criteria andMaterialSpecIsNull() {
			addCriterion("material_spec is null");
			return (Criteria) this;
		}

		public Criteria andMaterialSpecIsNotNull() {
			addCriterion("material_spec is not null");
			return (Criteria) this;
		}

		public Criteria andMaterialSpecEqualTo(String value) {
			addCriterion("material_spec =", value, "materialSpec");
			return (Criteria) this;
		}

		public Criteria andMaterialSpecNotEqualTo(String value) {
			addCriterion("material_spec <>", value, "materialSpec");
			return (Criteria) this;
		}

		public Criteria andMaterialSpecGreaterThan(String value) {
			addCriterion("material_spec >", value, "materialSpec");
			return (Criteria) this;
		}

		public Criteria andMaterialSpecGreaterThanOrEqualTo(String value) {
			addCriterion("material_spec >=", value, "materialSpec");
			return (Criteria) this;
		}

		public Criteria andMaterialSpecLessThan(String value) {
			addCriterion("material_spec <", value, "materialSpec");
			return (Criteria) this;
		}

		public Criteria andMaterialSpecLessThanOrEqualTo(String value) {
			addCriterion("material_spec <=", value, "materialSpec");
			return (Criteria) this;
		}

		public Criteria andMaterialSpecLike(String value) {
			addCriterion("material_spec like", value, "materialSpec");
			return (Criteria) this;
		}

		public Criteria andMaterialSpecNotLike(String value) {
			addCriterion("material_spec not like", value, "materialSpec");
			return (Criteria) this;
		}

		public Criteria andMaterialSpecIn(List<String> values) {
			addCriterion("material_spec in", values, "materialSpec");
			return (Criteria) this;
		}

		public Criteria andMaterialSpecNotIn(List<String> values) {
			addCriterion("material_spec not in", values, "materialSpec");
			return (Criteria) this;
		}

		public Criteria andMaterialSpecBetween(String value1, String value2) {
			addCriterion("material_spec between", value1, value2, "materialSpec");
			return (Criteria) this;
		}

		public Criteria andMaterialSpecNotBetween(String value1, String value2) {
			addCriterion("material_spec not between", value1, value2, "materialSpec");
			return (Criteria) this;
		}

		public Criteria andWarehousePositionIsNull() {
			addCriterion("warehouse_position is null");
			return (Criteria) this;
		}

		public Criteria andWarehousePositionIsNotNull() {
			addCriterion("warehouse_position is not null");
			return (Criteria) this;
		}

		public Criteria andWarehousePositionEqualTo(String value) {
			addCriterion("warehouse_position =", value, "warehousePosition");
			return (Criteria) this;
		}

		public Criteria andWarehousePositionNotEqualTo(String value) {
			addCriterion("warehouse_position <>", value, "warehousePosition");
			return (Criteria) this;
		}

		public Criteria andWarehousePositionGreaterThan(String value) {
			addCriterion("warehouse_position >", value, "warehousePosition");
			return (Criteria) this;
		}

		public Criteria andWarehousePositionGreaterThanOrEqualTo(String value) {
			addCriterion("warehouse_position >=", value, "warehousePosition");
			return (Criteria) this;
		}

		public Criteria andWarehousePositionLessThan(String value) {
			addCriterion("warehouse_position <", value, "warehousePosition");
			return (Criteria) this;
		}

		public Criteria andWarehousePositionLessThanOrEqualTo(String value) {
			addCriterion("warehouse_position <=", value, "warehousePosition");
			return (Criteria) this;
		}

		public Criteria andWarehousePositionLike(String value) {
			addCriterion("warehouse_position like", value, "warehousePosition");
			return (Criteria) this;
		}

		public Criteria andWarehousePositionNotLike(String value) {
			addCriterion("warehouse_position not like", value, "warehousePosition");
			return (Criteria) this;
		}

		public Criteria andWarehousePositionIn(List<String> values) {
			addCriterion("warehouse_position in", values, "warehousePosition");
			return (Criteria) this;
		}

		public Criteria andWarehousePositionNotIn(List<String> values) {
			addCriterion("warehouse_position not in", values, "warehousePosition");
			return (Criteria) this;
		}

		public Criteria andWarehousePositionBetween(String value1, String value2) {
			addCriterion("warehouse_position between", value1, value2, "warehousePosition");
			return (Criteria) this;
		}

		public Criteria andWarehousePositionNotBetween(String value1, String value2) {
			addCriterion("warehouse_position not between", value1, value2, "warehousePosition");
			return (Criteria) this;
		}

		public Criteria andPlusIsNull() {
			addCriterion("plus is null");
			return (Criteria) this;
		}

		public Criteria andPlusIsNotNull() {
			addCriterion("plus is not null");
			return (Criteria) this;
		}

		public Criteria andPlusEqualTo(String value) {
			addCriterion("plus =", value, "plus");
			return (Criteria) this;
		}

		public Criteria andPlusNotEqualTo(String value) {
			addCriterion("plus <>", value, "plus");
			return (Criteria) this;
		}

		public Criteria andPlusGreaterThan(String value) {
			addCriterion("plus >", value, "plus");
			return (Criteria) this;
		}

		public Criteria andPlusGreaterThanOrEqualTo(String value) {
			addCriterion("plus >=", value, "plus");
			return (Criteria) this;
		}

		public Criteria andPlusLessThan(String value) {
			addCriterion("plus <", value, "plus");
			return (Criteria) this;
		}

		public Criteria andPlusLessThanOrEqualTo(String value) {
			addCriterion("plus <=", value, "plus");
			return (Criteria) this;
		}

		public Criteria andPlusLike(String value) {
			addCriterion("plus like", value, "plus");
			return (Criteria) this;
		}

		public Criteria andPlusNotLike(String value) {
			addCriterion("plus not like", value, "plus");
			return (Criteria) this;
		}

		public Criteria andPlusIn(List<String> values) {
			addCriterion("plus in", values, "plus");
			return (Criteria) this;
		}

		public Criteria andPlusNotIn(List<String> values) {
			addCriterion("plus not in", values, "plus");
			return (Criteria) this;
		}

		public Criteria andPlusBetween(String value1, String value2) {
			addCriterion("plus between", value1, value2, "plus");
			return (Criteria) this;
		}

		public Criteria andPlusNotBetween(String value1, String value2) {
			addCriterion("plus not between", value1, value2, "plus");
			return (Criteria) this;
		}

		public Criteria andMaterialTypeIsNull() {
			addCriterion("material_type is null");
			return (Criteria) this;
		}

		public Criteria andMaterialTypeIsNotNull() {
			addCriterion("material_type is not null");
			return (Criteria) this;
		}

		public Criteria andMaterialTypeEqualTo(String value) {
			addCriterion("material_type =", value, "materialType");
			return (Criteria) this;
		}

		public Criteria andMaterialTypeNotEqualTo(String value) {
			addCriterion("material_type <>", value, "materialType");
			return (Criteria) this;
		}

		public Criteria andMaterialTypeGreaterThan(String value) {
			addCriterion("material_type >", value, "materialType");
			return (Criteria) this;
		}

		public Criteria andMaterialTypeGreaterThanOrEqualTo(String value) {
			addCriterion("material_type >=", value, "materialType");
			return (Criteria) this;
		}

		public Criteria andMaterialTypeLessThan(String value) {
			addCriterion("material_type <", value, "materialType");
			return (Criteria) this;
		}

		public Criteria andMaterialTypeLessThanOrEqualTo(String value) {
			addCriterion("material_type <=", value, "materialType");
			return (Criteria) this;
		}

		public Criteria andMaterialTypeLike(String value) {
			addCriterion("material_type like", value, "materialType");
			return (Criteria) this;
		}

		public Criteria andMaterialTypeNotLike(String value) {
			addCriterion("material_type not like", value, "materialType");
			return (Criteria) this;
		}

		public Criteria andMaterialTypeIn(List<String> values) {
			addCriterion("material_type in", values, "materialType");
			return (Criteria) this;
		}

		public Criteria andMaterialTypeNotIn(List<String> values) {
			addCriterion("material_type not in", values, "materialType");
			return (Criteria) this;
		}

		public Criteria andMaterialTypeBetween(String value1, String value2) {
			addCriterion("material_type between", value1, value2, "materialType");
			return (Criteria) this;
		}

		public Criteria andMaterialTypeNotBetween(String value1, String value2) {
			addCriterion("material_type not between", value1, value2, "materialType");
			return (Criteria) this;
		}

		public Criteria andMaterialUnitIsNull() {
			addCriterion("material_unit is null");
			return (Criteria) this;
		}

		public Criteria andMaterialUnitIsNotNull() {
			addCriterion("material_unit is not null");
			return (Criteria) this;
		}

		public Criteria andMaterialUnitEqualTo(String value) {
			addCriterion("material_unit =", value, "materialUnit");
			return (Criteria) this;
		}

		public Criteria andMaterialUnitNotEqualTo(String value) {
			addCriterion("material_unit <>", value, "materialUnit");
			return (Criteria) this;
		}

		public Criteria andMaterialUnitGreaterThan(String value) {
			addCriterion("material_unit >", value, "materialUnit");
			return (Criteria) this;
		}

		public Criteria andMaterialUnitGreaterThanOrEqualTo(String value) {
			addCriterion("material_unit >=", value, "materialUnit");
			return (Criteria) this;
		}

		public Criteria andMaterialUnitLessThan(String value) {
			addCriterion("material_unit <", value, "materialUnit");
			return (Criteria) this;
		}

		public Criteria andMaterialUnitLessThanOrEqualTo(String value) {
			addCriterion("material_unit <=", value, "materialUnit");
			return (Criteria) this;
		}

		public Criteria andMaterialUnitLike(String value) {
			addCriterion("material_unit like", value, "materialUnit");
			return (Criteria) this;
		}

		public Criteria andMaterialUnitNotLike(String value) {
			addCriterion("material_unit not like", value, "materialUnit");
			return (Criteria) this;
		}

		public Criteria andMaterialUnitIn(List<String> values) {
			addCriterion("material_unit in", values, "materialUnit");
			return (Criteria) this;
		}

		public Criteria andMaterialUnitNotIn(List<String> values) {
			addCriterion("material_unit not in", values, "materialUnit");
			return (Criteria) this;
		}

		public Criteria andMaterialUnitBetween(String value1, String value2) {
			addCriterion("material_unit between", value1, value2, "materialUnit");
			return (Criteria) this;
		}

		public Criteria andMaterialUnitNotBetween(String value1, String value2) {
			addCriterion("material_unit not between", value1, value2, "materialUnit");
			return (Criteria) this;
		}

		public Criteria andMaterialPriceIsNull() {
			addCriterion("material_price is null");
			return (Criteria) this;
		}

		public Criteria andMaterialPriceIsNotNull() {
			addCriterion("material_price is not null");
			return (Criteria) this;
		}

		public Criteria andMaterialPriceEqualTo(Float value) {
			addCriterion("material_price =", value, "materialPrice");
			return (Criteria) this;
		}

		public Criteria andMaterialPriceNotEqualTo(Float value) {
			addCriterion("material_price <>", value, "materialPrice");
			return (Criteria) this;
		}

		public Criteria andMaterialPriceGreaterThan(Float value) {
			addCriterion("material_price >", value, "materialPrice");
			return (Criteria) this;
		}

		public Criteria andMaterialPriceGreaterThanOrEqualTo(Float value) {
			addCriterion("material_price >=", value, "materialPrice");
			return (Criteria) this;
		}

		public Criteria andMaterialPriceLessThan(Float value) {
			addCriterion("material_price <", value, "materialPrice");
			return (Criteria) this;
		}

		public Criteria andMaterialPriceLessThanOrEqualTo(Float value) {
			addCriterion("material_price <=", value, "materialPrice");
			return (Criteria) this;
		}

		public Criteria andMaterialPriceIn(List<Float> values) {
			addCriterion("material_price in", values, "materialPrice");
			return (Criteria) this;
		}

		public Criteria andMaterialPriceNotIn(List<Float> values) {
			addCriterion("material_price not in", values, "materialPrice");
			return (Criteria) this;
		}

		public Criteria andMaterialPriceBetween(Float value1, Float value2) {
			addCriterion("material_price between", value1, value2, "materialPrice");
			return (Criteria) this;
		}

		public Criteria andMaterialPriceNotBetween(Float value1, Float value2) {
			addCriterion("material_price not between", value1, value2, "materialPrice");
			return (Criteria) this;
		}

		public Criteria andStockNumberIsNull() {
			addCriterion("stock_number is null");
			return (Criteria) this;
		}

		public Criteria andStockNumberIsNotNull() {
			addCriterion("stock_number is not null");
			return (Criteria) this;
		}

		public Criteria andStockNumberEqualTo(Integer value) {
			addCriterion("stock_number =", value, "stockNumber");
			return (Criteria) this;
		}

		public Criteria andStockNumberNotEqualTo(Integer value) {
			addCriterion("stock_number <>", value, "stockNumber");
			return (Criteria) this;
		}

		public Criteria andStockNumberGreaterThan(Integer value) {
			addCriterion("stock_number >", value, "stockNumber");
			return (Criteria) this;
		}

		public Criteria andStockNumberGreaterThanOrEqualTo(Integer value) {
			addCriterion("stock_number >=", value, "stockNumber");
			return (Criteria) this;
		}

		public Criteria andStockNumberLessThan(Integer value) {
			addCriterion("stock_number <", value, "stockNumber");
			return (Criteria) this;
		}

		public Criteria andStockNumberLessThanOrEqualTo(Integer value) {
			addCriterion("stock_number <=", value, "stockNumber");
			return (Criteria) this;
		}

		public Criteria andStockNumberIn(List<Integer> values) {
			addCriterion("stock_number in", values, "stockNumber");
			return (Criteria) this;
		}

		public Criteria andStockNumberNotIn(List<Integer> values) {
			addCriterion("stock_number not in", values, "stockNumber");
			return (Criteria) this;
		}

		public Criteria andStockNumberBetween(Integer value1, Integer value2) {
			addCriterion("stock_number between", value1, value2, "stockNumber");
			return (Criteria) this;
		}

		public Criteria andStockNumberNotBetween(Integer value1, Integer value2) {
			addCriterion("stock_number not between", value1, value2, "stockNumber");
			return (Criteria) this;
		}

		public Criteria andStockSafeIsNull() {
			addCriterion("stock_safe is null");
			return (Criteria) this;
		}

		public Criteria andStockSafeIsNotNull() {
			addCriterion("stock_safe is not null");
			return (Criteria) this;
		}

		public Criteria andStockSafeEqualTo(Integer value) {
			addCriterion("stock_safe =", value, "stockSafe");
			return (Criteria) this;
		}

		public Criteria andStockSafeNotEqualTo(Integer value) {
			addCriterion("stock_safe <>", value, "stockSafe");
			return (Criteria) this;
		}

		public Criteria andStockSafeGreaterThan(Integer value) {
			addCriterion("stock_safe >", value, "stockSafe");
			return (Criteria) this;
		}

		public Criteria andStockSafeGreaterThanOrEqualTo(Integer value) {
			addCriterion("stock_safe >=", value, "stockSafe");
			return (Criteria) this;
		}

		public Criteria andStockSafeLessThan(Integer value) {
			addCriterion("stock_safe <", value, "stockSafe");
			return (Criteria) this;
		}

		public Criteria andStockSafeLessThanOrEqualTo(Integer value) {
			addCriterion("stock_safe <=", value, "stockSafe");
			return (Criteria) this;
		}

		public Criteria andStockSafeIn(List<Integer> values) {
			addCriterion("stock_safe in", values, "stockSafe");
			return (Criteria) this;
		}

		public Criteria andStockSafeNotIn(List<Integer> values) {
			addCriterion("stock_safe not in", values, "stockSafe");
			return (Criteria) this;
		}

		public Criteria andStockSafeBetween(Integer value1, Integer value2) {
			addCriterion("stock_safe between", value1, value2, "stockSafe");
			return (Criteria) this;
		}

		public Criteria andStockSafeNotBetween(Integer value1, Integer value2) {
			addCriterion("stock_safe not between", value1, value2, "stockSafe");
			return (Criteria) this;
		}

		public Criteria andBatchManageIsNull() {
			addCriterion("batch_manage is null");
			return (Criteria) this;
		}

		public Criteria andBatchManageIsNotNull() {
			addCriterion("batch_manage is not null");
			return (Criteria) this;
		}

		public Criteria andBatchManageEqualTo(String value) {
			addCriterion("batch_manage =", value, "batchManage");
			return (Criteria) this;
		}

		public Criteria andBatchManageNotEqualTo(String value) {
			addCriterion("batch_manage <>", value, "batchManage");
			return (Criteria) this;
		}

		public Criteria andBatchManageGreaterThan(String value) {
			addCriterion("batch_manage >", value, "batchManage");
			return (Criteria) this;
		}

		public Criteria andBatchManageGreaterThanOrEqualTo(String value) {
			addCriterion("batch_manage >=", value, "batchManage");
			return (Criteria) this;
		}

		public Criteria andBatchManageLessThan(String value) {
			addCriterion("batch_manage <", value, "batchManage");
			return (Criteria) this;
		}

		public Criteria andBatchManageLessThanOrEqualTo(String value) {
			addCriterion("batch_manage <=", value, "batchManage");
			return (Criteria) this;
		}

		public Criteria andBatchManageLike(String value) {
			addCriterion("batch_manage like", value, "batchManage");
			return (Criteria) this;
		}

		public Criteria andBatchManageNotLike(String value) {
			addCriterion("batch_manage not like", value, "batchManage");
			return (Criteria) this;
		}

		public Criteria andBatchManageIn(List<String> values) {
			addCriterion("batch_manage in", values, "batchManage");
			return (Criteria) this;
		}

		public Criteria andBatchManageNotIn(List<String> values) {
			addCriterion("batch_manage not in", values, "batchManage");
			return (Criteria) this;
		}

		public Criteria andBatchManageBetween(String value1, String value2) {
			addCriterion("batch_manage between", value1, value2, "batchManage");
			return (Criteria) this;
		}

		public Criteria andBatchManageNotBetween(String value1, String value2) {
			addCriterion("batch_manage not between", value1, value2, "batchManage");
			return (Criteria) this;
		}

		public Criteria andFinanceIsNull() {
			addCriterion("finance is null");
			return (Criteria) this;
		}

		public Criteria andFinanceIsNotNull() {
			addCriterion("finance is not null");
			return (Criteria) this;
		}

		public Criteria andFinanceEqualTo(String value) {
			addCriterion("finance =", value, "finance");
			return (Criteria) this;
		}

		public Criteria andFinanceNotEqualTo(String value) {
			addCriterion("finance <>", value, "finance");
			return (Criteria) this;
		}

		public Criteria andFinanceGreaterThan(String value) {
			addCriterion("finance >", value, "finance");
			return (Criteria) this;
		}

		public Criteria andFinanceGreaterThanOrEqualTo(String value) {
			addCriterion("finance >=", value, "finance");
			return (Criteria) this;
		}

		public Criteria andFinanceLessThan(String value) {
			addCriterion("finance <", value, "finance");
			return (Criteria) this;
		}

		public Criteria andFinanceLessThanOrEqualTo(String value) {
			addCriterion("finance <=", value, "finance");
			return (Criteria) this;
		}

		public Criteria andFinanceLike(String value) {
			addCriterion("finance like", value, "finance");
			return (Criteria) this;
		}

		public Criteria andFinanceNotLike(String value) {
			addCriterion("finance not like", value, "finance");
			return (Criteria) this;
		}

		public Criteria andFinanceIn(List<String> values) {
			addCriterion("finance in", values, "finance");
			return (Criteria) this;
		}

		public Criteria andFinanceNotIn(List<String> values) {
			addCriterion("finance not in", values, "finance");
			return (Criteria) this;
		}

		public Criteria andFinanceBetween(String value1, String value2) {
			addCriterion("finance between", value1, value2, "finance");
			return (Criteria) this;
		}

		public Criteria andFinanceNotBetween(String value1, String value2) {
			addCriterion("finance not between", value1, value2, "finance");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(String value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(String value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(String value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(String value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(String value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(String value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLike(String value) {
			addCriterion("status like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotLike(String value) {
			addCriterion("status not like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<String> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<String> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(String value1, String value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(String value1, String value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andFinishTimeIsNull() {
			addCriterion("finish_time is null");
			return (Criteria) this;
		}

		public Criteria andFinishTimeIsNotNull() {
			addCriterion("finish_time is not null");
			return (Criteria) this;
		}

		public Criteria andFinishTimeEqualTo(Date value) {
			addCriterionForJDBCDate("finish_time =", value, "finishTime");
			return (Criteria) this;
		}

		public Criteria andFinishTimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("finish_time <>", value, "finishTime");
			return (Criteria) this;
		}

		public Criteria andFinishTimeGreaterThan(Date value) {
			addCriterionForJDBCDate("finish_time >", value, "finishTime");
			return (Criteria) this;
		}

		public Criteria andFinishTimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("finish_time >=", value, "finishTime");
			return (Criteria) this;
		}

		public Criteria andFinishTimeLessThan(Date value) {
			addCriterionForJDBCDate("finish_time <", value, "finishTime");
			return (Criteria) this;
		}

		public Criteria andFinishTimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("finish_time <=", value, "finishTime");
			return (Criteria) this;
		}

		public Criteria andFinishTimeIn(List<Date> values) {
			addCriterionForJDBCDate("finish_time in", values, "finishTime");
			return (Criteria) this;
		}

		public Criteria andFinishTimeNotIn(List<Date> values) {
			addCriterionForJDBCDate("finish_time not in", values, "finishTime");
			return (Criteria) this;
		}

		public Criteria andFinishTimeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("finish_time between", value1, value2, "finishTime");
			return (Criteria) this;
		}

		public Criteria andFinishTimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("finish_time not between", value1, value2, "finishTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeIsNull() {
			addCriterion("start_time is null");
			return (Criteria) this;
		}

		public Criteria andStartTimeIsNotNull() {
			addCriterion("start_time is not null");
			return (Criteria) this;
		}

		public Criteria andStartTimeEqualTo(Date value) {
			addCriterionForJDBCDate("start_time =", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("start_time <>", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeGreaterThan(Date value) {
			addCriterionForJDBCDate("start_time >", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("start_time >=", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeLessThan(Date value) {
			addCriterionForJDBCDate("start_time <", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("start_time <=", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeIn(List<Date> values) {
			addCriterionForJDBCDate("start_time in", values, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeNotIn(List<Date> values) {
			addCriterionForJDBCDate("start_time not in", values, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("start_time between", value1, value2, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("start_time not between", value1, value2, "startTime");
			return (Criteria) this;
		}

		public Criteria andCreateManagerIsNull() {
			addCriterion("create_manager is null");
			return (Criteria) this;
		}

		public Criteria andCreateManagerIsNotNull() {
			addCriterion("create_manager is not null");
			return (Criteria) this;
		}

		public Criteria andCreateManagerEqualTo(String value) {
			addCriterion("create_manager =", value, "createManager");
			return (Criteria) this;
		}

		public Criteria andCreateManagerNotEqualTo(String value) {
			addCriterion("create_manager <>", value, "createManager");
			return (Criteria) this;
		}

		public Criteria andCreateManagerGreaterThan(String value) {
			addCriterion("create_manager >", value, "createManager");
			return (Criteria) this;
		}

		public Criteria andCreateManagerGreaterThanOrEqualTo(String value) {
			addCriterion("create_manager >=", value, "createManager");
			return (Criteria) this;
		}

		public Criteria andCreateManagerLessThan(String value) {
			addCriterion("create_manager <", value, "createManager");
			return (Criteria) this;
		}

		public Criteria andCreateManagerLessThanOrEqualTo(String value) {
			addCriterion("create_manager <=", value, "createManager");
			return (Criteria) this;
		}

		public Criteria andCreateManagerLike(String value) {
			addCriterion("create_manager like", value, "createManager");
			return (Criteria) this;
		}

		public Criteria andCreateManagerNotLike(String value) {
			addCriterion("create_manager not like", value, "createManager");
			return (Criteria) this;
		}

		public Criteria andCreateManagerIn(List<String> values) {
			addCriterion("create_manager in", values, "createManager");
			return (Criteria) this;
		}

		public Criteria andCreateManagerNotIn(List<String> values) {
			addCriterion("create_manager not in", values, "createManager");
			return (Criteria) this;
		}

		public Criteria andCreateManagerBetween(String value1, String value2) {
			addCriterion("create_manager between", value1, value2, "createManager");
			return (Criteria) this;
		}

		public Criteria andCreateManagerNotBetween(String value1, String value2) {
			addCriterion("create_manager not between", value1, value2, "createManager");
			return (Criteria) this;
		}

		public Criteria andChangeTimeIsNull() {
			addCriterion("change_time is null");
			return (Criteria) this;
		}

		public Criteria andChangeTimeIsNotNull() {
			addCriterion("change_time is not null");
			return (Criteria) this;
		}

		public Criteria andChangeTimeEqualTo(Date value) {
			addCriterionForJDBCDate("change_time =", value, "changeTime");
			return (Criteria) this;
		}

		public Criteria andChangeTimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("change_time <>", value, "changeTime");
			return (Criteria) this;
		}

		public Criteria andChangeTimeGreaterThan(Date value) {
			addCriterionForJDBCDate("change_time >", value, "changeTime");
			return (Criteria) this;
		}

		public Criteria andChangeTimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("change_time >=", value, "changeTime");
			return (Criteria) this;
		}

		public Criteria andChangeTimeLessThan(Date value) {
			addCriterionForJDBCDate("change_time <", value, "changeTime");
			return (Criteria) this;
		}

		public Criteria andChangeTimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("change_time <=", value, "changeTime");
			return (Criteria) this;
		}

		public Criteria andChangeTimeIn(List<Date> values) {
			addCriterionForJDBCDate("change_time in", values, "changeTime");
			return (Criteria) this;
		}

		public Criteria andChangeTimeNotIn(List<Date> values) {
			addCriterionForJDBCDate("change_time not in", values, "changeTime");
			return (Criteria) this;
		}

		public Criteria andChangeTimeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("change_time between", value1, value2, "changeTime");
			return (Criteria) this;
		}

		public Criteria andChangeTimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("change_time not between", value1, value2, "changeTime");
			return (Criteria) this;
		}

		public Criteria andChangeManagerIsNull() {
			addCriterion("change_manager is null");
			return (Criteria) this;
		}

		public Criteria andChangeManagerIsNotNull() {
			addCriterion("change_manager is not null");
			return (Criteria) this;
		}

		public Criteria andChangeManagerEqualTo(String value) {
			addCriterion("change_manager =", value, "changeManager");
			return (Criteria) this;
		}

		public Criteria andChangeManagerNotEqualTo(String value) {
			addCriterion("change_manager <>", value, "changeManager");
			return (Criteria) this;
		}

		public Criteria andChangeManagerGreaterThan(String value) {
			addCriterion("change_manager >", value, "changeManager");
			return (Criteria) this;
		}

		public Criteria andChangeManagerGreaterThanOrEqualTo(String value) {
			addCriterion("change_manager >=", value, "changeManager");
			return (Criteria) this;
		}

		public Criteria andChangeManagerLessThan(String value) {
			addCriterion("change_manager <", value, "changeManager");
			return (Criteria) this;
		}

		public Criteria andChangeManagerLessThanOrEqualTo(String value) {
			addCriterion("change_manager <=", value, "changeManager");
			return (Criteria) this;
		}

		public Criteria andChangeManagerLike(String value) {
			addCriterion("change_manager like", value, "changeManager");
			return (Criteria) this;
		}

		public Criteria andChangeManagerNotLike(String value) {
			addCriterion("change_manager not like", value, "changeManager");
			return (Criteria) this;
		}

		public Criteria andChangeManagerIn(List<String> values) {
			addCriterion("change_manager in", values, "changeManager");
			return (Criteria) this;
		}

		public Criteria andChangeManagerNotIn(List<String> values) {
			addCriterion("change_manager not in", values, "changeManager");
			return (Criteria) this;
		}

		public Criteria andChangeManagerBetween(String value1, String value2) {
			addCriterion("change_manager between", value1, value2, "changeManager");
			return (Criteria) this;
		}

		public Criteria andChangeManagerNotBetween(String value1, String value2) {
			addCriterion("change_manager not between", value1, value2, "changeManager");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table xinyi_material
	 * @mbg.generated  Wed Jul 03 14:05:28 CST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table xinyi_material
     *
     * @mbg.generated do_not_delete_during_merge Wed Jul 03 12:53:13 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}