package com.xinyi.bean;

public class XinyiSupplierInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xinyi_supplier_info.id
     *
     * @mbg.generated Tue Jul 30 12:31:49 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xinyi_supplier_info.name
     *
     * @mbg.generated Tue Jul 30 12:31:49 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xinyi_supplier_info.telephone
     *
     * @mbg.generated Tue Jul 30 12:31:49 CST 2019
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xinyi_supplier_info.plus
     *
     * @mbg.generated Tue Jul 30 12:31:49 CST 2019
     */
    private String plus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xinyi_supplier_info.type
     *
     * @mbg.generated Tue Jul 30 12:31:49 CST 2019
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xinyi_supplier_info.manager
     *
     * @mbg.generated Tue Jul 30 12:31:49 CST 2019
     */
    private String manager;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xinyi_supplier_info.id
     *
     * @return the value of xinyi_supplier_info.id
     *
     * @mbg.generated Tue Jul 30 12:31:49 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xinyi_supplier_info.id
     *
     * @param id the value for xinyi_supplier_info.id
     *
     * @mbg.generated Tue Jul 30 12:31:49 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xinyi_supplier_info.name
     *
     * @return the value of xinyi_supplier_info.name
     *
     * @mbg.generated Tue Jul 30 12:31:49 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xinyi_supplier_info.name
     *
     * @param name the value for xinyi_supplier_info.name
     *
     * @mbg.generated Tue Jul 30 12:31:49 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xinyi_supplier_info.telephone
     *
     * @return the value of xinyi_supplier_info.telephone
     *
     * @mbg.generated Tue Jul 30 12:31:49 CST 2019
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xinyi_supplier_info.telephone
     *
     * @param telephone the value for xinyi_supplier_info.telephone
     *
     * @mbg.generated Tue Jul 30 12:31:49 CST 2019
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xinyi_supplier_info.plus
     *
     * @return the value of xinyi_supplier_info.plus
     *
     * @mbg.generated Tue Jul 30 12:31:49 CST 2019
     */
    public String getPlus() {
        return plus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xinyi_supplier_info.plus
     *
     * @param plus the value for xinyi_supplier_info.plus
     *
     * @mbg.generated Tue Jul 30 12:31:49 CST 2019
     */
    public void setPlus(String plus) {
        this.plus = plus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xinyi_supplier_info.type
     *
     * @return the value of xinyi_supplier_info.type
     *
     * @mbg.generated Tue Jul 30 12:31:49 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xinyi_supplier_info.type
     *
     * @param type the value for xinyi_supplier_info.type
     *
     * @mbg.generated Tue Jul 30 12:31:49 CST 2019
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xinyi_supplier_info.manager
     *
     * @return the value of xinyi_supplier_info.manager
     *
     * @mbg.generated Tue Jul 30 12:31:49 CST 2019
     */
    public String getManager() {
        return manager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xinyi_supplier_info.manager
     *
     * @param manager the value for xinyi_supplier_info.manager
     *
     * @mbg.generated Tue Jul 30 12:31:49 CST 2019
     */
    public void setManager(String manager) {
        this.manager = manager;
    }
}