package com.xinyi.bean;

public class XinyiImport {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_import.id
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_import.material_id
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	private String materialId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_import.vice_id
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	private String viceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_import.material_name
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	private String materialName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_import.material_spec
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	private String materialSpec;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_import.warehouse_position
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	private String warehousePosition;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_import.import_number
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	private Double importNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_import.price_include_tax
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	private Double priceIncludeTax;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_import.price
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	private Double price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_import.tax_rate
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	private Double taxRate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_import.size
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	private String size;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_import.tax
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	private Double tax;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_import.total_price_include_tax
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	private Double totalPriceIncludeTax;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_import.total_price
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	private Double totalPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_import.unit
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	private String unit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_import.batch_manage
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	private String batchManage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_import.supplier
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	private String supplier;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_import.manufacturing
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	private String manufacturing;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_import.plus
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	private String plus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_import.xinyi_inportcol
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	private String xinyiInportcol;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_import.id
	 * @return  the value of xinyi_import.id
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_import.id
	 * @param id  the value for xinyi_import.id
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_import.material_id
	 * @return  the value of xinyi_import.material_id
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	public String getMaterialId() {
		return materialId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_import.material_id
	 * @param materialId  the value for xinyi_import.material_id
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	public void setMaterialId(String materialId) {
		this.materialId = materialId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_import.vice_id
	 * @return  the value of xinyi_import.vice_id
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	public String getViceId() {
		return viceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_import.vice_id
	 * @param viceId  the value for xinyi_import.vice_id
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	public void setViceId(String viceId) {
		this.viceId = viceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_import.material_name
	 * @return  the value of xinyi_import.material_name
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	public String getMaterialName() {
		return materialName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_import.material_name
	 * @param materialName  the value for xinyi_import.material_name
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	public void setMaterialName(String materialName) {
		this.materialName = materialName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_import.material_spec
	 * @return  the value of xinyi_import.material_spec
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	public String getMaterialSpec() {
		return materialSpec;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_import.material_spec
	 * @param materialSpec  the value for xinyi_import.material_spec
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	public void setMaterialSpec(String materialSpec) {
		this.materialSpec = materialSpec;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_import.warehouse_position
	 * @return  the value of xinyi_import.warehouse_position
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	public String getWarehousePosition() {
		return warehousePosition;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_import.warehouse_position
	 * @param warehousePosition  the value for xinyi_import.warehouse_position
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	public void setWarehousePosition(String warehousePosition) {
		this.warehousePosition = warehousePosition;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_import.import_number
	 * @return  the value of xinyi_import.import_number
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	public Double getImportNumber() {
		return importNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_import.import_number
	 * @param importNumber  the value for xinyi_import.import_number
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	public void setImportNumber(Double importNumber) {
		this.importNumber = importNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_import.price_include_tax
	 * @return  the value of xinyi_import.price_include_tax
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	public Double getPriceIncludeTax() {
		return priceIncludeTax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_import.price_include_tax
	 * @param priceIncludeTax  the value for xinyi_import.price_include_tax
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	public void setPriceIncludeTax(Double priceIncludeTax) {
		this.priceIncludeTax = priceIncludeTax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_import.price
	 * @return  the value of xinyi_import.price
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	public Double getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_import.price
	 * @param price  the value for xinyi_import.price
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	public void setPrice(Double price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_import.tax_rate
	 * @return  the value of xinyi_import.tax_rate
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	public Double getTaxRate() {
		return taxRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_import.tax_rate
	 * @param taxRate  the value for xinyi_import.tax_rate
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	public void setTaxRate(Double taxRate) {
		this.taxRate = taxRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_import.size
	 * @return  the value of xinyi_import.size
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	public String getSize() {
		return size;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_import.size
	 * @param size  the value for xinyi_import.size
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	public void setSize(String size) {
		this.size = size;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_import.tax
	 * @return  the value of xinyi_import.tax
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	public Double getTax() {
		return tax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_import.tax
	 * @param tax  the value for xinyi_import.tax
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	public void setTax(Double tax) {
		this.tax = tax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_import.total_price_include_tax
	 * @return  the value of xinyi_import.total_price_include_tax
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	public Double getTotalPriceIncludeTax() {
		return totalPriceIncludeTax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_import.total_price_include_tax
	 * @param totalPriceIncludeTax  the value for xinyi_import.total_price_include_tax
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	public void setTotalPriceIncludeTax(Double totalPriceIncludeTax) {
		this.totalPriceIncludeTax = totalPriceIncludeTax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_import.total_price
	 * @return  the value of xinyi_import.total_price
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	public Double getTotalPrice() {
		return totalPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_import.total_price
	 * @param totalPrice  the value for xinyi_import.total_price
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	public void setTotalPrice(Double totalPrice) {
		this.totalPrice = totalPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_import.unit
	 * @return  the value of xinyi_import.unit
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	public String getUnit() {
		return unit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_import.unit
	 * @param unit  the value for xinyi_import.unit
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	public void setUnit(String unit) {
		this.unit = unit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_import.batch_manage
	 * @return  the value of xinyi_import.batch_manage
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	public String getBatchManage() {
		return batchManage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_import.batch_manage
	 * @param batchManage  the value for xinyi_import.batch_manage
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	public void setBatchManage(String batchManage) {
		this.batchManage = batchManage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_import.supplier
	 * @return  the value of xinyi_import.supplier
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	public String getSupplier() {
		return supplier;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_import.supplier
	 * @param supplier  the value for xinyi_import.supplier
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	public void setSupplier(String supplier) {
		this.supplier = supplier;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_import.manufacturing
	 * @return  the value of xinyi_import.manufacturing
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	public String getManufacturing() {
		return manufacturing;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_import.manufacturing
	 * @param manufacturing  the value for xinyi_import.manufacturing
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	public void setManufacturing(String manufacturing) {
		this.manufacturing = manufacturing;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_import.plus
	 * @return  the value of xinyi_import.plus
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	public String getPlus() {
		return plus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_import.plus
	 * @param plus  the value for xinyi_import.plus
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	public void setPlus(String plus) {
		this.plus = plus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_import.xinyi_inportcol
	 * @return  the value of xinyi_import.xinyi_inportcol
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	public String getXinyiInportcol() {
		return xinyiInportcol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_import.xinyi_inportcol
	 * @param xinyiInportcol  the value for xinyi_import.xinyi_inportcol
	 * @mbg.generated  Tue Feb 25 14:44:53 CST 2020
	 */
	public void setXinyiInportcol(String xinyiInportcol) {
		this.xinyiInportcol = xinyiInportcol;
	}
}