package com.xinyi.bean;

import java.util.Date;

public class XinyiModifyhistory {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_modifyhistory.modifyId
	 * @mbg.generated  Sun Jul 14 18:16:22 CST 2019
	 */
	private Integer modifyid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_modifyhistory.modifyname
	 * @mbg.generated  Sun Jul 14 18:16:22 CST 2019
	 */
	private String modifyname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_modifyhistory.modifytime
	 * @mbg.generated  Sun Jul 14 18:16:22 CST 2019
	 */
	private Date modifytime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_modifyhistory.modifymanager
	 * @mbg.generated  Sun Jul 14 18:16:22 CST 2019
	 */
	private String modifymanager;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_modifyhistory.materialname
	 * @mbg.generated  Sun Jul 14 18:16:22 CST 2019
	 */
	private String materialname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_modifyhistory.materialId
	 * @mbg.generated  Sun Jul 14 18:16:22 CST 2019
	 */
	private String materialid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_modifyhistory.materialunit
	 * @mbg.generated  Sun Jul 14 18:16:22 CST 2019
	 */
	private String materialunit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_modifyhistory.materialnumber
	 * @mbg.generated  Sun Jul 14 18:16:22 CST 2019
	 */
	private Integer materialnumber;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_modifyhistory.modifyId
	 * @return  the value of xinyi_modifyhistory.modifyId
	 * @mbg.generated  Sun Jul 14 18:16:22 CST 2019
	 */
	public Integer getModifyid() {
		return modifyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_modifyhistory.modifyId
	 * @param modifyid  the value for xinyi_modifyhistory.modifyId
	 * @mbg.generated  Sun Jul 14 18:16:22 CST 2019
	 */
	public void setModifyid(Integer modifyid) {
		this.modifyid = modifyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_modifyhistory.modifyname
	 * @return  the value of xinyi_modifyhistory.modifyname
	 * @mbg.generated  Sun Jul 14 18:16:22 CST 2019
	 */
	public String getModifyname() {
		return modifyname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_modifyhistory.modifyname
	 * @param modifyname  the value for xinyi_modifyhistory.modifyname
	 * @mbg.generated  Sun Jul 14 18:16:22 CST 2019
	 */
	public void setModifyname(String modifyname) {
		this.modifyname = modifyname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_modifyhistory.modifytime
	 * @return  the value of xinyi_modifyhistory.modifytime
	 * @mbg.generated  Sun Jul 14 18:16:22 CST 2019
	 */
	public Date getModifytime() {
		return modifytime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_modifyhistory.modifytime
	 * @param modifytime  the value for xinyi_modifyhistory.modifytime
	 * @mbg.generated  Sun Jul 14 18:16:22 CST 2019
	 */
	public void setModifytime(Date modifytime) {
		this.modifytime = modifytime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_modifyhistory.modifymanager
	 * @return  the value of xinyi_modifyhistory.modifymanager
	 * @mbg.generated  Sun Jul 14 18:16:22 CST 2019
	 */
	public String getModifymanager() {
		return modifymanager;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_modifyhistory.modifymanager
	 * @param modifymanager  the value for xinyi_modifyhistory.modifymanager
	 * @mbg.generated  Sun Jul 14 18:16:22 CST 2019
	 */
	public void setModifymanager(String modifymanager) {
		this.modifymanager = modifymanager;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_modifyhistory.materialname
	 * @return  the value of xinyi_modifyhistory.materialname
	 * @mbg.generated  Sun Jul 14 18:16:22 CST 2019
	 */
	public String getMaterialname() {
		return materialname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_modifyhistory.materialname
	 * @param materialname  the value for xinyi_modifyhistory.materialname
	 * @mbg.generated  Sun Jul 14 18:16:22 CST 2019
	 */
	public void setMaterialname(String materialname) {
		this.materialname = materialname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_modifyhistory.materialId
	 * @return  the value of xinyi_modifyhistory.materialId
	 * @mbg.generated  Sun Jul 14 18:16:22 CST 2019
	 */
	public String getMaterialid() {
		return materialid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_modifyhistory.materialId
	 * @param materialid  the value for xinyi_modifyhistory.materialId
	 * @mbg.generated  Sun Jul 14 18:16:22 CST 2019
	 */
	public void setMaterialid(String materialid) {
		this.materialid = materialid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_modifyhistory.materialunit
	 * @return  the value of xinyi_modifyhistory.materialunit
	 * @mbg.generated  Sun Jul 14 18:16:22 CST 2019
	 */
	public String getMaterialunit() {
		return materialunit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_modifyhistory.materialunit
	 * @param materialunit  the value for xinyi_modifyhistory.materialunit
	 * @mbg.generated  Sun Jul 14 18:16:22 CST 2019
	 */
	public void setMaterialunit(String materialunit) {
		this.materialunit = materialunit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_modifyhistory.materialnumber
	 * @return  the value of xinyi_modifyhistory.materialnumber
	 * @mbg.generated  Sun Jul 14 18:16:22 CST 2019
	 */
	public Integer getMaterialnumber() {
		return materialnumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_modifyhistory.materialnumber
	 * @param materialnumber  the value for xinyi_modifyhistory.materialnumber
	 * @mbg.generated  Sun Jul 14 18:16:22 CST 2019
	 */
	public void setMaterialnumber(Integer materialnumber) {
		this.materialnumber = materialnumber;
	}
}