package com.xinyi.bean;

public class XinyiRoles {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xinyi_roles.ROLE_ID
     *
     * @mbg.generated Fri May 24 23:04:22 CST 2019
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xinyi_roles.ROLE_NAME
     *
     * @mbg.generated Fri May 24 23:04:22 CST 2019
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xinyi_roles.ROLE_DESC
     *
     * @mbg.generated Fri May 24 23:04:22 CST 2019
     */
    private String roleDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xinyi_roles.ROLE_URL_PREFIX
     *
     * @mbg.generated Fri May 24 23:04:22 CST 2019
     */
    private String roleUrlPrefix;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xinyi_roles.ROLE_ID
     *
     * @return the value of xinyi_roles.ROLE_ID
     *
     * @mbg.generated Fri May 24 23:04:22 CST 2019
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xinyi_roles.ROLE_ID
     *
     * @param roleId the value for xinyi_roles.ROLE_ID
     *
     * @mbg.generated Fri May 24 23:04:22 CST 2019
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xinyi_roles.ROLE_NAME
     *
     * @return the value of xinyi_roles.ROLE_NAME
     *
     * @mbg.generated Fri May 24 23:04:22 CST 2019
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xinyi_roles.ROLE_NAME
     *
     * @param roleName the value for xinyi_roles.ROLE_NAME
     *
     * @mbg.generated Fri May 24 23:04:22 CST 2019
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xinyi_roles.ROLE_DESC
     *
     * @return the value of xinyi_roles.ROLE_DESC
     *
     * @mbg.generated Fri May 24 23:04:22 CST 2019
     */
    public String getRoleDesc() {
        return roleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xinyi_roles.ROLE_DESC
     *
     * @param roleDesc the value for xinyi_roles.ROLE_DESC
     *
     * @mbg.generated Fri May 24 23:04:22 CST 2019
     */
    public void setRoleDesc(String roleDesc) {
        this.roleDesc = roleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xinyi_roles.ROLE_URL_PREFIX
     *
     * @return the value of xinyi_roles.ROLE_URL_PREFIX
     *
     * @mbg.generated Fri May 24 23:04:22 CST 2019
     */
    public String getRoleUrlPrefix() {
        return roleUrlPrefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xinyi_roles.ROLE_URL_PREFIX
     *
     * @param roleUrlPrefix the value for xinyi_roles.ROLE_URL_PREFIX
     *
     * @mbg.generated Fri May 24 23:04:22 CST 2019
     */
    public void setRoleUrlPrefix(String roleUrlPrefix) {
        this.roleUrlPrefix = roleUrlPrefix;
    }
}