package com.xinyi.bean;

import java.util.Date;

public class XinyiPicking {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_picking.id
	 * @mbg.generated  Thu Aug 01 11:47:35 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_picking.materials
	 * @mbg.generated  Thu Aug 01 11:47:35 CST 2019
	 */
	private String materials;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_picking.name
	 * @mbg.generated  Thu Aug 01 11:47:35 CST 2019
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_picking.plus
	 * @mbg.generated  Thu Aug 01 11:47:35 CST 2019
	 */
	private String plus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_picking.time
	 * @mbg.generated  Thu Aug 01 11:47:35 CST 2019
	 */
	private Date time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_picking.baoxiu_id
	 * @mbg.generated  Thu Aug 01 11:47:35 CST 2019
	 */
	private String baoxiuId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_picking.fact_materials
	 * @mbg.generated  Thu Aug 01 11:47:35 CST 2019
	 */
	private String factMaterials;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_picking.id
	 * @return  the value of xinyi_picking.id
	 * @mbg.generated  Thu Aug 01 11:47:35 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_picking.id
	 * @param id  the value for xinyi_picking.id
	 * @mbg.generated  Thu Aug 01 11:47:35 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_picking.materials
	 * @return  the value of xinyi_picking.materials
	 * @mbg.generated  Thu Aug 01 11:47:35 CST 2019
	 */
	public String getMaterials() {
		return materials;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_picking.materials
	 * @param materials  the value for xinyi_picking.materials
	 * @mbg.generated  Thu Aug 01 11:47:35 CST 2019
	 */
	public void setMaterials(String materials) {
		this.materials = materials;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_picking.name
	 * @return  the value of xinyi_picking.name
	 * @mbg.generated  Thu Aug 01 11:47:35 CST 2019
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_picking.name
	 * @param name  the value for xinyi_picking.name
	 * @mbg.generated  Thu Aug 01 11:47:35 CST 2019
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_picking.plus
	 * @return  the value of xinyi_picking.plus
	 * @mbg.generated  Thu Aug 01 11:47:35 CST 2019
	 */
	public String getPlus() {
		return plus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_picking.plus
	 * @param plus  the value for xinyi_picking.plus
	 * @mbg.generated  Thu Aug 01 11:47:35 CST 2019
	 */
	public void setPlus(String plus) {
		this.plus = plus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_picking.time
	 * @return  the value of xinyi_picking.time
	 * @mbg.generated  Thu Aug 01 11:47:35 CST 2019
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_picking.time
	 * @param time  the value for xinyi_picking.time
	 * @mbg.generated  Thu Aug 01 11:47:35 CST 2019
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_picking.baoxiu_id
	 * @return  the value of xinyi_picking.baoxiu_id
	 * @mbg.generated  Thu Aug 01 11:47:35 CST 2019
	 */
	public String getBaoxiuId() {
		return baoxiuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_picking.baoxiu_id
	 * @param baoxiuId  the value for xinyi_picking.baoxiu_id
	 * @mbg.generated  Thu Aug 01 11:47:35 CST 2019
	 */
	public void setBaoxiuId(String baoxiuId) {
		this.baoxiuId = baoxiuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_picking.fact_materials
	 * @return  the value of xinyi_picking.fact_materials
	 * @mbg.generated  Thu Aug 01 11:47:35 CST 2019
	 */
	public String getFactMaterials() {
		return factMaterials;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_picking.fact_materials
	 * @param factMaterials  the value for xinyi_picking.fact_materials
	 * @mbg.generated  Thu Aug 01 11:47:35 CST 2019
	 */
	public void setFactMaterials(String factMaterials) {
		this.factMaterials = factMaterials;
	}
}