package com.xinyi.bean;

public class XinyiImage {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_image.id
	 * @mbg.generated  Tue Sep 10 19:58:49 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_image.material_id
	 * @mbg.generated  Tue Sep 10 19:58:49 CST 2019
	 */
	private String materialId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_image.image_name
	 * @mbg.generated  Tue Sep 10 19:58:49 CST 2019
	 */
	private String imageName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column xinyi_image.plus
	 * @mbg.generated  Tue Sep 10 19:58:49 CST 2019
	 */
	private String plus;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_image.id
	 * @return  the value of xinyi_image.id
	 * @mbg.generated  Tue Sep 10 19:58:49 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_image.id
	 * @param id  the value for xinyi_image.id
	 * @mbg.generated  Tue Sep 10 19:58:49 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_image.material_id
	 * @return  the value of xinyi_image.material_id
	 * @mbg.generated  Tue Sep 10 19:58:49 CST 2019
	 */
	public String getMaterialId() {
		return materialId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_image.material_id
	 * @param materialId  the value for xinyi_image.material_id
	 * @mbg.generated  Tue Sep 10 19:58:49 CST 2019
	 */
	public void setMaterialId(String materialId) {
		this.materialId = materialId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_image.image_name
	 * @return  the value of xinyi_image.image_name
	 * @mbg.generated  Tue Sep 10 19:58:49 CST 2019
	 */
	public String getImageName() {
		return imageName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_image.image_name
	 * @param imageName  the value for xinyi_image.image_name
	 * @mbg.generated  Tue Sep 10 19:58:49 CST 2019
	 */
	public void setImageName(String imageName) {
		this.imageName = imageName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column xinyi_image.plus
	 * @return  the value of xinyi_image.plus
	 * @mbg.generated  Tue Sep 10 19:58:49 CST 2019
	 */
	public String getPlus() {
		return plus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column xinyi_image.plus
	 * @param plus  the value for xinyi_image.plus
	 * @mbg.generated  Tue Sep 10 19:58:49 CST 2019
	 */
	public void setPlus(String plus) {
		this.plus = plus;
	}
}