package com.xinyi.bean;

public class XinyiManufactures {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xinyi_manufactures.id
     *
     * @mbg.generated Sun Jul 14 18:25:40 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xinyi_manufactures.name
     *
     * @mbg.generated Sun Jul 14 18:25:40 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xinyi_manufactures.plus
     *
     * @mbg.generated Sun Jul 14 18:25:40 CST 2019
     */
    private String plus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xinyi_manufactures.id
     *
     * @return the value of xinyi_manufactures.id
     *
     * @mbg.generated Sun Jul 14 18:25:40 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xinyi_manufactures.id
     *
     * @param id the value for xinyi_manufactures.id
     *
     * @mbg.generated Sun Jul 14 18:25:40 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xinyi_manufactures.name
     *
     * @return the value of xinyi_manufactures.name
     *
     * @mbg.generated Sun Jul 14 18:25:40 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xinyi_manufactures.name
     *
     * @param name the value for xinyi_manufactures.name
     *
     * @mbg.generated Sun Jul 14 18:25:40 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xinyi_manufactures.plus
     *
     * @return the value of xinyi_manufactures.plus
     *
     * @mbg.generated Sun Jul 14 18:25:40 CST 2019
     */
    public String getPlus() {
        return plus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xinyi_manufactures.plus
     *
     * @param plus the value for xinyi_manufactures.plus
     *
     * @mbg.generated Sun Jul 14 18:25:40 CST 2019
     */
    public void setPlus(String plus) {
        this.plus = plus;
    }
}