package com.xinyi.bean;

public class XinyiUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xinyi_user.USER_ID
     *
     * @mbg.generated Fri May 24 23:04:22 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xinyi_user.USER_USERNAME
     *
     * @mbg.generated Fri May 24 23:04:22 CST 2019
     */
    private String userUsername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xinyi_user.USER_PASSWORD
     *
     * @mbg.generated Fri May 24 23:04:22 CST 2019
     */
    private String userPassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xinyi_user.USER_ID
     *
     * @return the value of xinyi_user.USER_ID
     *
     * @mbg.generated Fri May 24 23:04:22 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xinyi_user.USER_ID
     *
     * @param userId the value for xinyi_user.USER_ID
     *
     * @mbg.generated Fri May 24 23:04:22 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xinyi_user.USER_USERNAME
     *
     * @return the value of xinyi_user.USER_USERNAME
     *
     * @mbg.generated Fri May 24 23:04:22 CST 2019
     */
    public String getUserUsername() {
        return userUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xinyi_user.USER_USERNAME
     *
     * @param userUsername the value for xinyi_user.USER_USERNAME
     *
     * @mbg.generated Fri May 24 23:04:22 CST 2019
     */
    public void setUserUsername(String userUsername) {
        this.userUsername = userUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xinyi_user.USER_PASSWORD
     *
     * @return the value of xinyi_user.USER_PASSWORD
     *
     * @mbg.generated Fri May 24 23:04:22 CST 2019
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xinyi_user.USER_PASSWORD
     *
     * @param userPassword the value for xinyi_user.USER_PASSWORD
     *
     * @mbg.generated Fri May 24 23:04:22 CST 2019
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }
}