package com.xinyi.bean;

public class XinyiUserRoleKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xinyi_user_role.role_id
     *
     * @mbg.generated Sat May 25 19:44:58 CST 2019
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xinyi_user_role.user_id
     *
     * @mbg.generated Sat May 25 19:44:58 CST 2019
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xinyi_user_role.role_id
     *
     * @return the value of xinyi_user_role.role_id
     *
     * @mbg.generated Sat May 25 19:44:58 CST 2019
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xinyi_user_role.role_id
     *
     * @param roleId the value for xinyi_user_role.role_id
     *
     * @mbg.generated Sat May 25 19:44:58 CST 2019
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xinyi_user_role.user_id
     *
     * @return the value of xinyi_user_role.user_id
     *
     * @mbg.generated Sat May 25 19:44:58 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xinyi_user_role.user_id
     *
     * @param userId the value for xinyi_user_role.user_id
     *
     * @mbg.generated Sat May 25 19:44:58 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}