package com.xinyi.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class XinyiPickingExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table xinyi_picking
	 * @mbg.generated  Thu Aug 01 11:47:35 CST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table xinyi_picking
	 * @mbg.generated  Thu Aug 01 11:47:35 CST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table xinyi_picking
	 * @mbg.generated  Thu Aug 01 11:47:35 CST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_picking
	 * @mbg.generated  Thu Aug 01 11:47:35 CST 2019
	 */
	public XinyiPickingExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_picking
	 * @mbg.generated  Thu Aug 01 11:47:35 CST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_picking
	 * @mbg.generated  Thu Aug 01 11:47:35 CST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_picking
	 * @mbg.generated  Thu Aug 01 11:47:35 CST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_picking
	 * @mbg.generated  Thu Aug 01 11:47:35 CST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_picking
	 * @mbg.generated  Thu Aug 01 11:47:35 CST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_picking
	 * @mbg.generated  Thu Aug 01 11:47:35 CST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_picking
	 * @mbg.generated  Thu Aug 01 11:47:35 CST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_picking
	 * @mbg.generated  Thu Aug 01 11:47:35 CST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_picking
	 * @mbg.generated  Thu Aug 01 11:47:35 CST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table xinyi_picking
	 * @mbg.generated  Thu Aug 01 11:47:35 CST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table xinyi_picking
	 * @mbg.generated  Thu Aug 01 11:47:35 CST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andMaterialsIsNull() {
			addCriterion("materials is null");
			return (Criteria) this;
		}

		public Criteria andMaterialsIsNotNull() {
			addCriterion("materials is not null");
			return (Criteria) this;
		}

		public Criteria andMaterialsEqualTo(String value) {
			addCriterion("materials =", value, "materials");
			return (Criteria) this;
		}

		public Criteria andMaterialsNotEqualTo(String value) {
			addCriterion("materials <>", value, "materials");
			return (Criteria) this;
		}

		public Criteria andMaterialsGreaterThan(String value) {
			addCriterion("materials >", value, "materials");
			return (Criteria) this;
		}

		public Criteria andMaterialsGreaterThanOrEqualTo(String value) {
			addCriterion("materials >=", value, "materials");
			return (Criteria) this;
		}

		public Criteria andMaterialsLessThan(String value) {
			addCriterion("materials <", value, "materials");
			return (Criteria) this;
		}

		public Criteria andMaterialsLessThanOrEqualTo(String value) {
			addCriterion("materials <=", value, "materials");
			return (Criteria) this;
		}

		public Criteria andMaterialsLike(String value) {
			addCriterion("materials like", value, "materials");
			return (Criteria) this;
		}

		public Criteria andMaterialsNotLike(String value) {
			addCriterion("materials not like", value, "materials");
			return (Criteria) this;
		}

		public Criteria andMaterialsIn(List<String> values) {
			addCriterion("materials in", values, "materials");
			return (Criteria) this;
		}

		public Criteria andMaterialsNotIn(List<String> values) {
			addCriterion("materials not in", values, "materials");
			return (Criteria) this;
		}

		public Criteria andMaterialsBetween(String value1, String value2) {
			addCriterion("materials between", value1, value2, "materials");
			return (Criteria) this;
		}

		public Criteria andMaterialsNotBetween(String value1, String value2) {
			addCriterion("materials not between", value1, value2, "materials");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andPlusIsNull() {
			addCriterion("plus is null");
			return (Criteria) this;
		}

		public Criteria andPlusIsNotNull() {
			addCriterion("plus is not null");
			return (Criteria) this;
		}

		public Criteria andPlusEqualTo(String value) {
			addCriterion("plus =", value, "plus");
			return (Criteria) this;
		}

		public Criteria andPlusNotEqualTo(String value) {
			addCriterion("plus <>", value, "plus");
			return (Criteria) this;
		}

		public Criteria andPlusGreaterThan(String value) {
			addCriterion("plus >", value, "plus");
			return (Criteria) this;
		}

		public Criteria andPlusGreaterThanOrEqualTo(String value) {
			addCriterion("plus >=", value, "plus");
			return (Criteria) this;
		}

		public Criteria andPlusLessThan(String value) {
			addCriterion("plus <", value, "plus");
			return (Criteria) this;
		}

		public Criteria andPlusLessThanOrEqualTo(String value) {
			addCriterion("plus <=", value, "plus");
			return (Criteria) this;
		}

		public Criteria andPlusLike(String value) {
			addCriterion("plus like", value, "plus");
			return (Criteria) this;
		}

		public Criteria andPlusNotLike(String value) {
			addCriterion("plus not like", value, "plus");
			return (Criteria) this;
		}

		public Criteria andPlusIn(List<String> values) {
			addCriterion("plus in", values, "plus");
			return (Criteria) this;
		}

		public Criteria andPlusNotIn(List<String> values) {
			addCriterion("plus not in", values, "plus");
			return (Criteria) this;
		}

		public Criteria andPlusBetween(String value1, String value2) {
			addCriterion("plus between", value1, value2, "plus");
			return (Criteria) this;
		}

		public Criteria andPlusNotBetween(String value1, String value2) {
			addCriterion("plus not between", value1, value2, "plus");
			return (Criteria) this;
		}

		public Criteria andTimeIsNull() {
			addCriterion("time is null");
			return (Criteria) this;
		}

		public Criteria andTimeIsNotNull() {
			addCriterion("time is not null");
			return (Criteria) this;
		}

		public Criteria andTimeEqualTo(Date value) {
			addCriterion("time =", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeNotEqualTo(Date value) {
			addCriterion("time <>", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeGreaterThan(Date value) {
			addCriterion("time >", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("time >=", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeLessThan(Date value) {
			addCriterion("time <", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeLessThanOrEqualTo(Date value) {
			addCriterion("time <=", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeIn(List<Date> values) {
			addCriterion("time in", values, "time");
			return (Criteria) this;
		}

		public Criteria andTimeNotIn(List<Date> values) {
			addCriterion("time not in", values, "time");
			return (Criteria) this;
		}

		public Criteria andTimeBetween(Date value1, Date value2) {
			addCriterion("time between", value1, value2, "time");
			return (Criteria) this;
		}

		public Criteria andTimeNotBetween(Date value1, Date value2) {
			addCriterion("time not between", value1, value2, "time");
			return (Criteria) this;
		}

		public Criteria andBaoxiuIdIsNull() {
			addCriterion("baoxiu_id is null");
			return (Criteria) this;
		}

		public Criteria andBaoxiuIdIsNotNull() {
			addCriterion("baoxiu_id is not null");
			return (Criteria) this;
		}

		public Criteria andBaoxiuIdEqualTo(String value) {
			addCriterion("baoxiu_id =", value, "baoxiuId");
			return (Criteria) this;
		}

		public Criteria andBaoxiuIdNotEqualTo(String value) {
			addCriterion("baoxiu_id <>", value, "baoxiuId");
			return (Criteria) this;
		}

		public Criteria andBaoxiuIdGreaterThan(String value) {
			addCriterion("baoxiu_id >", value, "baoxiuId");
			return (Criteria) this;
		}

		public Criteria andBaoxiuIdGreaterThanOrEqualTo(String value) {
			addCriterion("baoxiu_id >=", value, "baoxiuId");
			return (Criteria) this;
		}

		public Criteria andBaoxiuIdLessThan(String value) {
			addCriterion("baoxiu_id <", value, "baoxiuId");
			return (Criteria) this;
		}

		public Criteria andBaoxiuIdLessThanOrEqualTo(String value) {
			addCriterion("baoxiu_id <=", value, "baoxiuId");
			return (Criteria) this;
		}

		public Criteria andBaoxiuIdLike(String value) {
			addCriterion("baoxiu_id like", value, "baoxiuId");
			return (Criteria) this;
		}

		public Criteria andBaoxiuIdNotLike(String value) {
			addCriterion("baoxiu_id not like", value, "baoxiuId");
			return (Criteria) this;
		}

		public Criteria andBaoxiuIdIn(List<String> values) {
			addCriterion("baoxiu_id in", values, "baoxiuId");
			return (Criteria) this;
		}

		public Criteria andBaoxiuIdNotIn(List<String> values) {
			addCriterion("baoxiu_id not in", values, "baoxiuId");
			return (Criteria) this;
		}

		public Criteria andBaoxiuIdBetween(String value1, String value2) {
			addCriterion("baoxiu_id between", value1, value2, "baoxiuId");
			return (Criteria) this;
		}

		public Criteria andBaoxiuIdNotBetween(String value1, String value2) {
			addCriterion("baoxiu_id not between", value1, value2, "baoxiuId");
			return (Criteria) this;
		}

		public Criteria andFactMaterialsIsNull() {
			addCriterion("fact_materials is null");
			return (Criteria) this;
		}

		public Criteria andFactMaterialsIsNotNull() {
			addCriterion("fact_materials is not null");
			return (Criteria) this;
		}

		public Criteria andFactMaterialsEqualTo(String value) {
			addCriterion("fact_materials =", value, "factMaterials");
			return (Criteria) this;
		}

		public Criteria andFactMaterialsNotEqualTo(String value) {
			addCriterion("fact_materials <>", value, "factMaterials");
			return (Criteria) this;
		}

		public Criteria andFactMaterialsGreaterThan(String value) {
			addCriterion("fact_materials >", value, "factMaterials");
			return (Criteria) this;
		}

		public Criteria andFactMaterialsGreaterThanOrEqualTo(String value) {
			addCriterion("fact_materials >=", value, "factMaterials");
			return (Criteria) this;
		}

		public Criteria andFactMaterialsLessThan(String value) {
			addCriterion("fact_materials <", value, "factMaterials");
			return (Criteria) this;
		}

		public Criteria andFactMaterialsLessThanOrEqualTo(String value) {
			addCriterion("fact_materials <=", value, "factMaterials");
			return (Criteria) this;
		}

		public Criteria andFactMaterialsLike(String value) {
			addCriterion("fact_materials like", value, "factMaterials");
			return (Criteria) this;
		}

		public Criteria andFactMaterialsNotLike(String value) {
			addCriterion("fact_materials not like", value, "factMaterials");
			return (Criteria) this;
		}

		public Criteria andFactMaterialsIn(List<String> values) {
			addCriterion("fact_materials in", values, "factMaterials");
			return (Criteria) this;
		}

		public Criteria andFactMaterialsNotIn(List<String> values) {
			addCriterion("fact_materials not in", values, "factMaterials");
			return (Criteria) this;
		}

		public Criteria andFactMaterialsBetween(String value1, String value2) {
			addCriterion("fact_materials between", value1, value2, "factMaterials");
			return (Criteria) this;
		}

		public Criteria andFactMaterialsNotBetween(String value1, String value2) {
			addCriterion("fact_materials not between", value1, value2, "factMaterials");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table xinyi_picking
	 * @mbg.generated  Thu Aug 01 11:47:35 CST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table xinyi_picking
     *
     * @mbg.generated do_not_delete_during_merge Sat Jul 20 12:41:32 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}