package com.xinyi.bean;

public class XinyiAction {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xinyi_action.ACTION_ID
     *
     * @mbg.generated Fri May 24 23:04:22 CST 2019
     */
    private Integer actionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xinyi_action.ACTION_NAME
     *
     * @mbg.generated Fri May 24 23:04:22 CST 2019
     */
    private String actionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xinyi_action.action_desc
     *
     * @mbg.generated Fri May 24 23:04:22 CST 2019
     */
    private String actionDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xinyi_action.action_param
     *
     * @mbg.generated Fri May 24 23:04:22 CST 2019
     */
    private String actionParam;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xinyi_action.ACTION_ID
     *
     * @return the value of xinyi_action.ACTION_ID
     *
     * @mbg.generated Fri May 24 23:04:22 CST 2019
     */
    public Integer getActionId() {
        return actionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xinyi_action.ACTION_ID
     *
     * @param actionId the value for xinyi_action.ACTION_ID
     *
     * @mbg.generated Fri May 24 23:04:22 CST 2019
     */
    public void setActionId(Integer actionId) {
        this.actionId = actionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xinyi_action.ACTION_NAME
     *
     * @return the value of xinyi_action.ACTION_NAME
     *
     * @mbg.generated Fri May 24 23:04:22 CST 2019
     */
    public String getActionName() {
        return actionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xinyi_action.ACTION_NAME
     *
     * @param actionName the value for xinyi_action.ACTION_NAME
     *
     * @mbg.generated Fri May 24 23:04:22 CST 2019
     */
    public void setActionName(String actionName) {
        this.actionName = actionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xinyi_action.action_desc
     *
     * @return the value of xinyi_action.action_desc
     *
     * @mbg.generated Fri May 24 23:04:22 CST 2019
     */
    public String getActionDesc() {
        return actionDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xinyi_action.action_desc
     *
     * @param actionDesc the value for xinyi_action.action_desc
     *
     * @mbg.generated Fri May 24 23:04:22 CST 2019
     */
    public void setActionDesc(String actionDesc) {
        this.actionDesc = actionDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xinyi_action.action_param
     *
     * @return the value of xinyi_action.action_param
     *
     * @mbg.generated Fri May 24 23:04:22 CST 2019
     */
    public String getActionParam() {
        return actionParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xinyi_action.action_param
     *
     * @param actionParam the value for xinyi_action.action_param
     *
     * @mbg.generated Fri May 24 23:04:22 CST 2019
     */
    public void setActionParam(String actionParam) {
        this.actionParam = actionParam;
    }
}